import {escapeHtml as esc, marineIcon, faqSchema, signup} from './site-chrome.mjs';

export const aboutUpdated = '2026-09-23';
// Add identity details only when the founders supply them; never infer them from namesakes.
const company = {
  founders: [{name:'Charles',initial:'C'}, {name:'Marc',initial:'M'}],
  founded: null,
  socials: []
};
const source = (url,label) => `<a class="about-source" href="${url}" target="_blank" rel="noopener">${label} ↗</a>`;
const intercom = 'https://www.intercom.com/pricing';
const crisp = 'https://crisp.chat/en/pricing/';
const crispWorkspaces = 'https://help.crisp.chat/en/article/how-to-split-incoming-conversations-into-multiple-workspaces-5aej8s/';
const services = [
  ['orca','One live chat for multiple products','Bring conversations from your SaaS products, apps and stores into one shared inbox. Each conversation keeps its project context, so your team can answer across the portfolio without opening a different support tab for every product.','/features','Explore the workspace'],
  ['shark','Orky: drafts, automatic replies and human takeover','Reply yourself, ask Orky to prepare a draft, or let it answer from your product knowledge. You choose where AI steps in and can take over when a question needs human judgment.','/ai','Meet Orky'],
  ['shell','A multilingual help center','Publish Markdown articles on your own domain, organize collections and translate content automatically, with manual corrections available. Customers can find answers on the public help center or inside the widget, and the same articles help inform Orky.','/help-center','See the help center'],
  ['compass','Visitor context and the Orka SDK','See who is visiting and connect the attributes your app already knows, such as plan, installation date, usage tier or merchant details. Your integration supplies the data, helping your team ask fewer repetitive questions and start with the right context.','/sdk','Explore custom visitor data'],
  ['anchor','Teamwork that keeps the conversation together','Assign conversations, leave private notes, mention a teammate and set reminders. Project access controls help each person focus on the products they support while keeping handovers in the same thread.','/features','See the team tools'],
  ['coral','Support across languages and working hours','Two-way translation keeps original and translated messages together; away status and night, break-day or emergency banners set expectations. Follow conversations with Orka’s iOS and Android apps when you are away from your desk, without promising that a human is available around the clock.','/ios-app','Take Orka with you']
];
const differences = [
  ['∞','Projects on every plan','Unlimited projects, including on Solo','Orka includes unlimited projects in one inbox on its free Solo plan as well as Pod and Fleet. Crisp also supports multi-site setups, but its documentation distinguishes independent chatboxes with separate workspace IDs from sub-inboxes for teams inside one workspace. Our focus is a portfolio of products with their own context, answered from one place.',source(crispWorkspaces,'Crisp’s workspace documentation')],
  ['$29','Up to 3 teammates','Team plans with the seat count in plain sight','Orka Pod is $29 per month for up to three people; Fleet is $99 for up to twenty. Intercom prices its helpdesk per seat, while Orka publishes a fixed subscription for each of those team sizes. AI usage and taxes are separate, and these plans do not offer identical feature sets.',source(intercom,'Intercom’s seat pricing')],
  ['$0','Help center entry price','Knowledge is part of the starting point','Orka includes a multilingual help center and custom-domain publishing on every plan, including free Solo. Crisp lists its knowledge base in Essentials at $95 per month per workspace. That gives a solo Orka founder a way to publish useful answers before taking on a paid team subscription.',source(crisp,'Crisp’s plan inclusions')],
  ['0%','Orka markup on your key','Two clear ways to pay for AI','Bring your own provider key and Orka adds no markup, or use managed AI at the named model’s standard API rate multiplied by two. Intercom Fin advertises outcome-based pricing from $0.99 per outcome. Tokens and outcomes are different units, so we show a conversation calculator rather than promise that one model of billing always costs less.',source(intercom,'Intercom’s AI pricing')],
  ['2','Founders behind the product','A small team, deliberately close to the work','Charles and Marc build and support Orka, bootstrapped in France with no outsourced support. We focus on founders and small teams; Intercom’s Expert plan, for example, lists enterprise identity management and SLAs for different requirements. If self-hosting, native phone support or a complex contact center is essential, read our limits before choosing Orka.',source(intercom,'Intercom’s enterprise features')]
];
const audiences = [
  ['Solo founders with several SaaS products','One person maintaining a main business, a side project and the next launch.'],
  ['Small product teams of 2–20 people','A shared support crew handling customers across several apps or brands.'],
  ['Shopify app developers with a portfolio','Teams supporting merchants across booking, download, translation, bundle or other apps.'],
  ['Owners of multiple online stores','A small crew answering product, sizing, delivery and policy questions across shops.'],
  ['Vibe coding founders','Builders shipping with Lovable, Bolt, Replit, Base44 or v0 who want an existing support system for each new app.'],
  ['Small agencies supporting client projects','Teams that need project context and scoped teammate access, rather than another support login for every website.']
];
export const aboutFaqs = [
  ['What is Orka?','Orka is a live chat and shared customer-support inbox for founders and small teams running multiple products. It combines conversations, visitor context, a multilingual help center and an optional AI agent called Orky.'],
  ['Who owns and builds Orka?','Orka is owned and operated by BIGMO SAS in France. Its co-founders, Charles and Marc, build and support the product without outsourced support.'],
  ['Why did the founders create Orka?','Charles and Marc were running their own products and needed to answer customers without constantly changing support workspaces. Orka started with that everyday problem and the desire to make room for evenings, days off and life outside the inbox.'],
  ['Can I use one Orka inbox for different businesses or products?','Yes. Every Orka plan includes unlimited projects, with project context on conversations and access controls for teammates. You can answer the shared queue or filter by project when you want to focus.'],
  ['Is Orka free, and what do the paid plans cost?','Solo is free for one person; Pod is $29 per month for up to three people; Fleet is $99 per month for up to twenty. Each includes unlimited projects and the multilingual help center, while AI usage is separate.'],
  ['Do I have to use AI to answer customers?','No. You can answer yourself, review and send an Orky draft, or enable automatic replies where appropriate. You remain responsible for customer commitments and can take over a conversation.'],
  ['Does Orka serve 35,500 businesses?','The 35,500+ businesses in 145+ countries figure refers to the Shopify apps built by the team behind Orka. It is not an Orka customer count.'],
  ['How do I get help from the Orka team?','Use the Orka chat widget on this website or email hello@orka.chat to reach the team. Charles and Marc provide support; the widget shows current availability, and we do not promise a fixed human response time or 24/7 human coverage.'],
  ['Is Orka suitable for an enterprise contact center?','Orka is designed for founders and small teams supporting multiple products. If you require self-hosting, native phone support, enterprise identity management or a complex contact center, it probably is not the right fit.']
];

function keyFacts(){
  const founders=company.founders.map(f=>esc(f.name)).join(' &amp; ');
  return [
    ['Company Name','Orka · owned and operated by BIGMO SAS'],
    ['Type','Bootstrapped, hosted customer-support software (SaaS)'],
    ['Founded',company.founded ? esc(company.founded) : 'Launch year not published. Originally built for the founders’ own products.'],
    ['Founder',founders+' · co-founders'],
    ['Headquarters','France · company address: 14 Rue Charles IV, 75004 Paris, France'],
    ['Website','<a href="https://orka.chat/">orka.chat</a>'],
    ['Core Offering','One live chat and shared support inbox for multiple SaaS products, apps, stores and projects'],
    ['Pricing','Solo: free / 1 person. Pod: $29 per month / up to 3 people. Fleet: $99 per month / up to 20. USD; AI usage and taxes separate. <a href="/pricing">Plan details ↗</a>'],
    ['Contract Terms','Monthly plans. Billing, renewal and cancellation terms are presented at purchase; cancellation is available through account controls or by contacting the team. <a href="/terms">Full terms ↗</a>'],
    ['Services','Live chat, shared inbox, Orky AI, help center, translation, visitor context, JavaScript SDK, teamwork tools and mobile apps'],
    ['Communication','Website chat widget and <a href="mailto:hello@orka.chat">hello@orka.chat</a> · support by Charles and Marc'],
    ['Notable Clients','Apps using Orka include Cowlendar, BIG Digital Downloads, EZ Product Image Translate and Rapi Bundles. <a href="/best-live-chat-for-shopify-apps">See the examples ↗</a>'],
    ['Customers Served','The team’s Shopify apps are used by 35,500+ businesses in 145+ countries. This is not a count of Orka customers.'],
    ['Projects Delivered','Orka is a software product, not a project-delivery agency. Customers can connect unlimited projects on every plan.'],
    ['Competitors','Crisp, Intercom, Tidio, tawk.to, Help Scout, Zendesk and other customer-support tools. <a href="/compare">Compare options ↗</a>'],
    ['Social',company.socials.length ? company.socials.map(s=>`<a href="${esc(s.url)}" rel="me noopener">${esc(s.label)} ↗</a>`).join(' · ') : '<a href="https://github.com/charlesmdp/orka" target="_blank" rel="noopener">Orka’s website repository on GitHub ↗</a>']
  ];
}
function organizationSchema(){
  const organization={'@type':'Organization','@id':'https://orka.chat/#organization',name:'Orka',legalName:'BIGMO SAS',url:'https://orka.chat/',logo:'https://orka.chat/assets/orka-logo.svg',email:'hello@orka.chat',description:'Live chat and a shared customer-support inbox for founders and small teams running multiple SaaS products, apps and stores.',founder:company.founders.map(f=>({'@type':'Person',name:f.name})),address:{'@type':'PostalAddress',streetAddress:'14 Rue Charles IV',postalCode:'75004',addressLocality:'Paris',addressCountry:'FR'},contactPoint:{'@type':'ContactPoint',contactType:'customer support',email:'hello@orka.chat',url:'https://orka.chat/about'}};
  if(company.founded)organization.foundingDate=company.founded;
  if(company.socials.length)organization.sameAs=company.socials.map(s=>s.url);
  return `<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':[organization,{'@type':'AboutPage','@id':'https://orka.chat/about#page',url:'https://orka.chat/about',name:'About Orka: live chat for multiple products',mainEntity:{'@id':'https://orka.chat/#organization'},dateModified:aboutUpdated}]}).replaceAll('<','\\u003c')}</script>`;
}

export function aboutBody(){return `<div class="about-page">
<section class="about-hero ed-wrap"><div class="about-hero-copy"><span class="ed-kicker">ABOUT ORKA · BUILT IN FRANCE</span><h1>About Orka.<br>One inbox.<br><em>Many products.</em></h1><p class="about-value"><strong>Orka is a live chat and customer-support platform that brings every product into one shared inbox for founders and small teams running multiple SaaS products, apps and stores.</strong></p><p>We built it for our own working days. And, just as importantly, for the hours after them.</p><div class="about-actions"><a class="ed-button lime" href="${signup}">Start free · No card required ↗</a><a href="#team">Meet Charles &amp; Marc ↓</a></div></div><div class="about-illustration" role="img" aria-label="A SaaS, a Shopify app and a new project all feed one Orka inbox, supported by Charles and Marc"><div class="about-art-top"><span>YOUR PRODUCTS. ONE POD.</span><span aria-hidden="true">BUILT IN FRANCE</span></div><div class="about-product-tiles"><span>${marineIcon('sail')}<b>Your SaaS</b></span><span>${marineIcon('shell')}<b>Your Shopify app</b></span><span>${marineIcon('shark')}<b>Your next idea</b></span></div><div class="about-joining-lines" aria-hidden="true"><i></i><i></i><i></i></div><div class="about-inbox"><div class="about-inbox-brand"><img src="/assets/orka-logo.svg" alt="" width="40" height="38"><strong>One shared inbox</strong><span>LIVE</span></div><div><span class="about-message-dot"></span><b>“Can you help me with my plan?”</b><small>Your SaaS</small></div><div><span class="about-message-dot"></span><b>“How do I set this up?”</b><small>Your Shopify app</small></div><div class="about-inbox-bottom"><span>All projects, together.</span><img src="/assets/orky-head-v2.svg" width="49" height="39" alt=""></div></div><div class="about-crew-note"><span>C</span><span>M</span><p>Built by Charles &amp; Marc.<br><b>Support stays with the builders.</b></p></div></div></section>
<div class="about-strip"><div class="ed-wrap"><span><b>∞</b> Projects on every plan</span><span><b>2</b> Founders behind Orka</span><span><b>0</b> Outsourced support teams</span></div></div>
<nav class="about-toc ed-wrap" aria-label="On this page"><a href="#what-we-do">What we do</a><a href="#different">Our differences</a><a href="#who-uses">Who it’s for</a><a href="#team">The team</a><a href="#how-it-works">Getting started</a><a href="#key-facts">Key facts</a><a href="#about-faq">FAQ</a></nav>
<section class="about-section ed-wrap" id="what-we-do"><div class="about-heading"><span class="ed-kicker">01 / THE WORKSPACE</span><h2>What Orka does</h2><p>Everything around a conversation, kept close to the person who needs an answer.</p></div><div class="about-services">${services.map(([icon,title,copy,url,label])=>`<article>${marineIcon(icon)}<h3>${title}</h3><p>${copy}</p><a href="${url}">${label} ↗</a></article>`).join('')}</div></section>
<section class="about-differences" id="different"><div class="ed-wrap"><div class="about-heading"><span class="ed-kicker">02 / OUR OWN LITTLE CORNER OF THE OCEAN</span><h2>What makes Orka different</h2><p>A few concrete choices. Not a claim that every other tool is wrong for you.</p></div><div>${differences.map(([metric,label,title,copy,citation],i)=>`<article class="about-difference"><div class="about-difference-number"><span>0${i+1}</span><strong>${metric}</strong><small>${label}</small></div><div><h3>${title}</h3><p>${copy}</p>${citation}</div></article>`).join('')}</div><p class="about-research-note">Competitor details checked 23 September 2026 on the official pages linked above. Plans can change; compare the complete scope and billing terms. Spot a mistake? <a href="mailto:hello@orka.chat">hello@orka.chat</a>.</p></div></section>
<section class="about-section ed-wrap" id="who-uses"><div class="about-heading"><span class="ed-kicker">03 / PEOPLE WITH MORE THAN ONE THING GOING ON</span><h2>Who uses Orka</h2><p>The strongest fit is a small crew supporting a growing portfolio.</p></div><div class="about-audience-layout"><ul class="about-audiences">${audiences.map(([name,copy])=>`<li><span aria-hidden="true">↗</span><div><strong>${name}</strong><p>${copy}</p></div></li>`).join('')}</ul><aside class="about-fit"><img src="/assets/orky-head-v2.svg" width="108" height="86" alt="Orky"><h3>A good fit.<br>Not every fit.</h3><p>You can start with one product. But if you need self-hosting, phone support, enterprise identity management or a complex contact center, another tool may serve you better.</p><a href="/is-orka-right-for-you">Read our product limits ↗</a></aside></div></section>
<section class="about-team" id="team"><div class="ed-wrap"><div class="about-heading"><span class="ed-kicker">04 / THE HUMANS ON THE OTHER SIDE</span><h2>The team behind Orka</h2><p>Built and supported by Charles &amp; Marc.<br>Bootstrapped in France. No outsourced support.</p></div><div class="about-founder-grid">${company.founders.map((f,i)=>`<article class="about-founder"><div class="about-founder-top"><span class="about-monogram" aria-hidden="true">${f.initial}.</span>${marineIcon(i?'shark':'orca')}</div><span class="ed-kicker">CO-FOUNDER · BUILDER · SUPPORT</span><h3>${esc(f.name)}</h3><p>${i?'Marc co-founded Orka with Charles and builds and supports the product. Their experience comes from running their own apps and online businesses, with the customer questions that come with them.':'Charles co-founded Orka after experiencing the cost and friction of supporting several products in separate workspaces. In his founder letter, he explains why late-night messages helped shape Orka’s approach to human availability and optional AI support.'}</p>${i?'<a href="mailto:hello@orka.chat">Reach the team ↗</a>':'<a href="/#story">Read Charles’s letter ↗</a>'}</article>`).join('')}</div><div class="about-origin"><div><span class="ed-kicker">HOW IT STARTED</span><h3>Built for us. Opened to you.</h3></div><p>Orka began as a tool for the founders’ own SaaS products and online businesses: one place to answer, with room to be unavailable sometimes. That experience became a hosted product for other founders and small teams facing the same juggling act.</p></div><div class="about-team-proof"><div><strong>35,500+</strong><span>businesses using the team’s Shopify apps</span></div><div><strong>145+</strong><span>countries reached by those apps</span></div><p>These figures describe the Shopify apps built by our team. They are not Orka’s customer count.</p></div></div></section>
<section class="about-section ed-wrap" id="how-it-works"><div class="about-heading"><span class="ed-kicker">05 / COME ABOARD</span><h2>How Orka works</h2><p>A self-service start, with the people who build it close by.</p></div><ol class="about-onboarding">${[
 ['Create your workspace','Start with free Solo and create a project for your first product. Add further projects to the same inbox as you need them.'],
 ['Install and test your chat','Copy your project’s snippet into the website or app you control, or use the Shopify store app. Send a test message and reply before considering the installation finished.'],
 ['Bring in your knowledge and crew','Publish or import your help articles, connect visitor attributes through the SDK where useful, and invite teammates with the right project access. Start with human replies or reviewed Orky drafts before enabling automatic replies.'],
 ['Keep building, keep answering','Work from the browser or Orka’s mobile apps. Set availability and expected reply times so your customers know what to expect while your team is busy or offline.']
 ].map(([title,copy],i)=>`<li><span>0${i+1}</span><h3>${title}</h3><p>${copy}</p></li>`).join('')}</ol><div class="about-support"><div>${marineIcon('buoy')}<h3>When you need our help</h3></div><p>Use the live chat on this website or email <a href="mailto:hello@orka.chat">hello@orka.chat</a>. You work with the team behind the product, including Charles and Marc; the widget shows current availability, with no fixed human response-time or 24/7 human-support promise.</p><p>Onboarding is self-service. Installation time depends on your platform and permissions, and a custom SDK integration may need development work. Our <a href="/installation">installation guides</a> cover the setup and checks; there is no standard project-delivery turnaround to buy.</p></div></section>
<section class="about-facts" id="key-facts"><div class="ed-wrap"><div class="about-heading"><span class="ed-kicker">06 / THE FACTS, IN ONE PLACE</span><h2>Key facts</h2><p>Orka at a glance. Updated September 2026.</p></div><table><caption>Company, product and contact details for Orka</caption><tbody>${keyFacts().map(([label,value])=>`<tr><th scope="row">${label}</th><td>${value}</td></tr>`).join('')}</tbody></table><a class="about-markdown" href="/about.md">Read this page as Markdown ↗</a></div></section>
<section class="about-section ed-wrap" id="about-faq"><div class="about-heading"><span class="ed-kicker">07 / A FEW THINGS WORTH ASKING</span><h2>Frequently asked questions</h2></div><div class="about-faq-grid">${aboutFaqs.map(([q,a],i)=>`<article>${marineIcon(['orca','shell','compass','shark','anchor','coral'][i%6])}<h3>${esc(q)}</h3><p>${esc(a)}</p></article>`).join('')}</div><div class="about-last-question"><img src="/assets/orky-head-v2.svg" alt="" width="72" height="58"><div><h3>One more question?</h3><p>Open the chat in the corner of this page, or write to the people behind Orka.</p></div><a href="mailto:hello@orka.chat">hello@orka.chat ↗</a></div></section>
<section class="about-final"><div class="ed-wrap"><span class="ed-kicker">FOR THE PEOPLE BEHIND EVERY PRODUCT</span><h2>Build the next thing.<br><em>Keep your support together.</em></h2><a class="ed-button lime" href="${signup}">Start free · No card required ↗</a><a href="/pricing">See plans and pricing ↗</a></div></section>
</div>${organizationSchema()}${faqSchema(aboutFaqs)}`;}
