import {builderPlatforms} from './builder-platforms.mjs';
import {exampleSnippet} from './installation-content.mjs';
import {escapeHtml as e,signup,marineIcon,faqSection,faqSchema} from './site-chrome.mjs';

export const builderSlugs=builderPlatforms.map(g=>g.slug);
export function builderDirectory(){return `<section class="ed-wrap builder-directory"><span class="ed-kicker">BUILT WITH AI. SUPPORTED BY YOU.</span><h2>Pick the tool you build with.</h2><p>A practical installation guide for each builder, with a prompt you can copy.</p><div>${builderPlatforms.map(g=>`<a href="/${g.slug}" style="--builder-color:${g.color}"><span class="builder-wordmark">${g.name}</span><span>Add live chat <b>↗</b></span></a>`).join('')}</div></section>`;}
function prompt(g){return `Install the real Orka live chat in this ${g.name} web app using the complete snippet I paste below.

1. Inspect the framework and shared layout first. Tell me where you will install it.
2. Preserve my ORKA_APP_ID and the official widget.orka.chat/app.js URL.
3. Load the widget once, asynchronously, in the browser after the document body exists. Keep it across client-side route changes. Prevent duplicate scripts or iframes.
4. If this is Next.js, use next/script with a stable ID and afterInteractive loading, or a browser-only client integration. Never access window during server rendering.
5. Keep the current design, authentication and backend. Do not create an imitation chat UI, install a second chat service or expose any private API key.
6. Check the build and explain how I can test a message and reply on the published app. Show the changed files. Do not publish until I have reviewed the change.

Here is the complete snippet copied from Orka → Settings → my project → Installation:
[PASTE YOUR COMPLETE ORKA SNIPPET HERE]`;}
function copyPanel(id,label,value,language='text'){return `<div class="guide-snippet builder-copy"><div><span>${label}</span><button type="button" data-copy-snippet="${id}">Copy ${language==='html'?'example':'prompt'}</button></div><pre tabindex="0"><code id="${id}" tabindex="-1">${e(value)}</code></pre></div>`;}
function sources(g){return `<section class="ed-wrap guide-sources"><span class="ed-kicker">OFFICIAL DOCUMENTATION</span><h2>Check the details at the source.</h2><p>Updated 21 September 2026. This is Orka’s installation guidance using the platform’s documented editing and publishing workflow, not a claim of a native partnership. Menus and plan limits can change. Corrections: <a href="mailto:hello@orka.chat">hello@orka.chat</a>.</p><ul>${g.sources.map(([name,url])=>`<li><a href="${url}" target="_blank" rel="noopener">${name} ↗</a></li>`).join('')}</ul></section>`;}
function builderBody(g){
 const faqs=[
  [`Can I add live chat to a ${g.name} app without knowing how to code?`,`Yes, an AI-assisted installation is a reasonable starting point. Copy your real Orka snippet, give ${g.name} the prompt in this guide and review the result. You still need access to edit and publish the project, and you should test a complete conversation. Ask for help if the integration fails instead of repeatedly pasting the script.`],
  ['Where is the Orka installation code?','In your Orka dashboard, go to Settings, choose the project and open Installation. Click Copy Code under How to embed. Use a separate project for each product whose branding and support context you want to keep separate.'],
  [`Is this a native ${g.name} integration?`,'This guide installs the standard Orka JavaScript widget into your web app. It does not require a dedicated marketplace connector. Platform editing permissions, publishing limits and support for custom code still apply.'],
  ['Will the chat survive navigation in my app?','It should if the loader is installed once in a persistent shared layout. Test several client-side routes and a direct reload of an inner page. Use the SPA guide if you also need controlled loading and user-session data.'],
  ['Does this guide install live chat in a native mobile app?','No. These steps are for a browser-based web app. A native iOS or Android app needs an appropriate embedded web integration; do not paste a browser script into a native view and expect it to run. See our mobile-app guides.'],
  ['Can I manage several AI-built apps in one inbox?','Yes. All Orka plans include unlimited projects. Give each product its own project and snippet, then answer together in the shared inbox or filter by project. Solo is free for one person; AI usage is separate.'],
  ['Does adding the widget give Orky access to my entire app database?','No. The widget does not automatically turn your database into AI knowledge. Configure help articles and AI behavior separately. For support context such as a plan or onboarding stage, explicitly send the relevant fields through the Orka SDK.']
 ];
 return `<section class="builder-hero" style="--builder-color:${g.color}"><div class="ed-wrap"><a class="c-back" href="/installation">← Installation guides</a><div class="builder-hero-grid"><div><span class="ed-kicker">${g.name.toUpperCase()} · PRACTICAL INSTALLATION GUIDE</span><h1>How to add live chat<br>to a <em>${g.name} app.</em></h1><p class="ed-lead">${g.lead}</p><a class="ed-button lime" href="#install">Install it step by step ↓</a><span class="builder-date">Web apps · Updated September 2026</span></div><div class="builder-scene"><div class="builder-scene-top"><span class="builder-wordmark">${g.name}</span><span>Your next product</span><i>● ● ●</i></div><div class="builder-scene-page"><span class="builder-scene-label">${g.scenario}</span><div class="builder-skeleton"><i></i><i></i><i></i></div><div class="builder-scene-chat"><img src="/assets/orky-head-v2.svg" width="48" height="38" alt="Orky"><p>${g.question}</p><span>Sent to your Orka inbox <b>✓</b></span></div></div><div class="builder-scene-bottom">${marineIcon('orca')}Same inbox. One more product aboard.</div></div></div></div></section><nav class="c-jump" aria-label="Guide sections"><div class="ed-wrap"><a href="#install">The steps</a><a href="#copy-prompt">Copy the prompt</a><a href="#test">Test it</a><a href="#troubleshoot">Fix a problem</a><a href="#faq">FAQ</a></div></nav>
 <section class="ed-wrap builder-route"><div><span>YOU NEED</span><strong>An Orka project + permission to edit and publish your ${g.name} app</strong></div><div><span>YOU WILL ADD</span><strong>One official widget script in the shared app layout</strong></div><div><span>YOU WILL CHECK</span><strong>A real message, a real reply and navigation between pages</strong></div></section>
 <section class="ed-wrap builder-install" id="install"><div class="guide-steps"><span class="ed-kicker">FROM FIRST PROMPT TO FIRST HELLO</span><h2>Bring your ${g.name} app aboard.</h2><article><span class="guide-step-number">01</span><div><h3>Copy your project’s snippet</h3><p>Open <a href="http://dashboard.orka.chat/">Orka</a> → Settings → your project → Installation. Under How to embed, click Copy Code. For a new product, create its own project first. This keeps the welcome, knowledge and conversations tied to the right app.</p></div></article>${[['Ask '+g.name+' to install it',g.entry],['Choose the right shared location',g.detail],['Review the change',g.inspect],['Publish the app',g.publish]].map(([title,copy],i)=>`<article><span class="guide-step-number">0${i+2}</span><div><h3>${title}</h3><p>${copy}</p></div></article>`).join('')}</div><aside><div class="builder-aside-note">${marineIcon('buoy')}<h3>Your project ID matters.</h3><p>The example below uses a placeholder. Copy the full snippet from your own Installation screen before asking ${g.name} to use it.</p></div>${copyPanel('builder-snippet','ORKA WIDGET · EXAMPLE',exampleSnippet,'html')}<p class="builder-small">The project ID identifies your widget. An OpenAI, Anthropic or other private API key does not belong in this code. Configure AI separately in Orka.</p><a class="builder-text-link" href="/how-to-add-orka-to-single-page-application">Using client-side routes? Read the SPA guide ↗</a></aside></section>
 <section class="builder-prompt-band" id="copy-prompt"><div class="ed-wrap"><div><span class="ed-kicker">LESS GUESSWORK FOR YOUR ASSISTANT</span><h2>Copy this prompt.<br><em>Add your real snippet.</em></h2><p>It tells ${g.name} what to install, what to preserve and how to avoid common mistakes. Replace the final placeholder before sending it.</p></div>${copyPanel('builder-prompt',g.name.toUpperCase()+' INSTALLATION PROMPT',prompt(g))}</div></section>
 <section class="ed-wrap builder-test" id="test"><div><span class="ed-kicker">DON’T STOP AT “DONE”</span><h2>Make the first conversation yours.</h2><p>Use a test visitor on the published app. The assistant saying it has installed chat is only the beginning of verification.</p></div><ol><li><strong>Open the public URL.</strong> Check desktop and mobile. If the app requires login, test the intended signed-in experience.</li><li><strong>Send “${g.name} installation test”.</strong> Confirm it arrives in the correct Orka project, then reply and check the visitor receives it.</li><li><strong>Navigate without refreshing.</strong> Visit two inner pages, use Back, then reload an inner URL. Check for duplicate bubbles or a lost conversation.</li><li><strong>Check the rest of your app.</strong> The chat should not cover a save button, checkout action or mobile navigation. Correct the placement if it does.</li></ol></section>
 <section class="ed-wrap builder-troubleshoot" id="troubleshoot"><span class="ed-kicker">IF SOMETHING FEELS OFF</span><h2>Three checks before another prompt.</h2><div>${[[g.trap,g.fix],['The widget is missing everywhere.','Confirm you used the complete snippet with the correct project ID. Check that the release includes the changed file. Review console errors, content security policy and consent settings; do not disable your site’s security rules to make the widget appear.'],['The message arrives under the wrong product.','Compare the installed ORKA_APP_ID with this product’s Installation screen. Replace the incorrect installation instead of adding another one. Then publish and send a new test message.']].map(([q,a])=>`<article>${marineIcon('compass')}<h3>${e(q)}</h3><p>${e(a)}</p></article>`).join('')}</div></section>
 <section class="ed-wrap builder-next"><img src="/assets/orky-head-v2.svg" width="75" height="60" alt="Orky"><div><h2>The next step: useful customer context.</h2><p>Once chat works, your app can send ${g.context} through the Orka SDK. Choose fields that help support; the widget does not infer them for you.</p><a href="/sdk">Explore the visitor-data SDK ↗</a></div><a class="ed-button lime" href="${signup}">Start free · No card required</a></section>${faqSection(faqs,{title:`Live chat in ${g.name}:<br>your questions.`})}${faqSchema(faqs)}${sources(g)}${builderDirectory()}`;
}
export function builderGuidePages(){return builderPlatforms.map(g=>({slug:g.slug,title:`How to add live chat to a ${g.name} app`,description:`Add Orka live chat to your ${g.name} web app. Copy an AI prompt, install the project snippet once, publish, test messages and fix common problems.`,body:builderBody(g)}));}
