const s=(title,text,sources=[])=>({title,paragraphs:text.trim().split('\n\n'),sources});
const source=(title,url)=>({title,url});
export const comparisons = [
{
 id:'intercom', name:'Intercom', color:'#B5C9FF', symbol:'↗', theme:'A smaller crew. A different kind of ship.',
 intro:'Intercom brings a broad customer-service platform. Orka brings your websites, people and knowledge into one approachable workspace. The right choice depends on how much infrastructure your support team actually needs.',
 bestOrka:'Several projects, a small team and a free multilingual help center.', bestRival:'Advanced service operations, enterprise controls and a broad channel mix.',
 priceNote:'Monthly Intercom seat prices; annual billing is cheaper. Fin outcomes, Copilot, channel usage, taxes and other add-ons are excluded. Early Stage discounts may change your comparison.', defaultPlan:0,
 sources:[source('Intercom plans and billing','https://www.intercom.com/help/en/articles/9061614-fin-and-intercom-plans-explained'),source('Intercom pricing and feature matrix','https://www.intercom.com/pricing'),source('Intercom Help Center','https://www.intercom.com/helpdesk/help-center'),source('Intercom Inbox','https://www.intercom.com/helpdesk/inbox')],
 proof:{'live-chat':['Live chat and in-app support',0],'email-follow-up':['Support email',0],'shared-inbox':['Shared inbox; multibrand varies by plan',1],'assignment':['Routing; advanced workflows depend on plan',1],'analytics':['Reports; real-time dashboard on Expert',0],'knowledge':['Fin uses support knowledge',2],'automatic-replies':['Fin; outcome charges apply',0],'ai-drafts':['Copilot add-on',1],'human-takeover':['Fin-to-human handoff',0],'translation':['Automatic translation; allowances apply',1],'help-center':['Public help center',1],'multilingual-help':['Advanced and Expert',1],'help-domain':['Customizable help center',2],'help-ai':['Help content supports Fin',2],'night-banner':['Office hours on Expert',0],'reply-time':['Team reply settings on Expert',0],'sdk':['Integration and API tools',0]},
 sections:[
 s('Start with the shape of your business.',`A founder running a booking app, a small shop and a side project has a different support problem from a company with several support departments. The founder needs to know which website someone came from and answer without losing an afternoon. A larger service operation may need formal routing rules, workload controls and a dependable way to report on different teams. Neither situation is more legitimate. They simply put different weight on the feature list.

Our reading is that Orka is a natural shortlist candidate for the first situation. Unlimited projects belong to the same subscription, with one person on Solo, three on Pod or twenty on Fleet. Intercom deserves serious consideration for the second: its published plans explicitly distinguish core support from workflow and enterprise capabilities. Do not pay for organizational complexity merely because it sounds impressive; do not remove it if your operation depends on it.`,[0]),
 s('Seat pricing changes the conversation.',`Intercom lists monthly seats at $39 for Essential, $99 for Advanced and $139 for Expert. Annual commitments reduce those figures to $29, $85 and $132 per seat per month. The calculator uses monthly billing so that the commitment matches Orka’s monthly plan prices. Three Essential seats therefore produce a $117 base subscription before usage. Orka Pod is $29 for up to three people. These are base prices, not a promise that the products provide identical service.

A more useful exercise is to select the Intercom tier you actually need before moving the team slider. If multilingual knowledge or a particular workflow sends you to another plan, the cheapest seat is not your real comparison. Conversely, an eligible startup discount or a negotiated agreement can narrow the difference. Put your actual offer beside the calculator before deciding to migrate.`,[0,1]),
 s('A help center belongs in the comparison.',`Orka includes a public, multilingual help center even on its free plan. You can write in Markdown, organize collections and sections, publish on a custom domain, and make articles available inside the chat widget. Automatic translations remain editable, and changes to the source mark translations as outdated. The same published knowledge helps Orky answer. For a tiny team, putting those jobs together makes documentation a practical part of support rather than a separate project.

Intercom also has a real help center. Public help content is part of its offering, with multilingual and private help centers appearing in higher plans. Its knowledge and support tools can be valuable when your team already works there. The distinction is therefore access, plan fit and the way you maintain content, not whether Intercom understands self-service. If you switch, review imported links, article structure and translations before replacing the old destination.`,[1,2]),
 s('Tokens and outcomes are different measurements.',`Fin starts at $0.99 per outcome. That is a different billing unit from Orka’s model-specific token usage. An outcome can follow the rules described in Intercom’s billing documentation; it should not casually be relabeled as a fixed number of messages. Orka’s managed AI uses the published model rates multiplied by two, with input and output counted separately. You can also bring your own provider key without an Orka markup.

There is no honest universal conversion from one outcome to one thousand tokens. A short answer and a long exchange with background knowledge use different amounts of context. Use a sample of your real questions, inspect the quality and record the actual usage. Our AI calculator explains the token calculation separately rather than manufacturing an attractive cost per conversation. The lower invoice is useful only if the answers and handovers work for your customers.`,[0]),
 s('Where Intercom may be the better choice.',`Intercom’s Expert plan lists capabilities such as service-level agreements, workload management and multibrand support. Its platform also offers channels whose usage is billed separately, including phone, SMS and WhatsApp. Those are meaningful capabilities when support is more than the conversation happening on your website. They can make the platform worth its price for a team that needs a structured service operation.

Orka’s current catalogue does not establish an equivalent enterprise SLA system, a complete phone contact center or automated account actions across all those channels. We are not quietly awarding Orka a checkmark for them. If any is mandatory, ask for a demonstration of the exact workflow before selecting Orka. The same applies to security requirements: a friendly chat interface is not evidence of a particular certification, identity system or regulated-data agreement.`,[0]),
 s('Try a handover, not just a perfect answer.',`A useful trial starts with a question your documents answer, then introduces an exception. Ask whether a customer can cancel after a deadline. Have the assistant explain the general policy, then ask it to make an exception that requires a person. In Orka, compare an AI draft you approve with an automatic reply and a human takeover. Add a private note so the next teammate does not have to reconstruct the situation.

Then repeat the exercise in Intercom using the plan and configuration you would buy. Measure the number of clicks, the clarity of the handoff and whether the customer has to repeat the problem. Do not grade the tools only on a smooth greeting. The awkward second question is often where support software earns its place. Bring your least convenient real example; a useful comparison should survive it.`),
 s('Our recommendation for a small, growing team.',`Choose Orka when keeping several projects approachable matters more than assembling an enterprise support operation. The free help center, shared context, visible human replies and predictable team tiers are the starting point. You can add AI without turning every person in the company into a paid AI seat. You can also keep the AI in draft mode while your documentation matures.

Choose Intercom when its broader workflows, channels and controls solve specific needs you can name. If you already rely on those tools, price the work of replacing them as well as the subscription. Neither a spreadsheet full of checkmarks nor a cheerful orca should decide on its own. Ask which setup helps the team answer accurately on an ordinary busy Tuesday, then use the numbers as one part of that decision.`)
 ]
},
{
 id:'tidio',name:'Tidio',color:'#B8DFFF',symbol:'◔',theme:'A good conversation. A clear choice.',
 intro:'Tidio combines live chat, Lyro AI and Flows. Orka combines a multi-project inbox, a free help center and an AI teammate. Here is how to compare the tools without mixing their allowances.',
 bestOrka:'Multiple projects and editable multilingual knowledge in one subscription.',bestRival:'Teams who want Tidio’s live chat, Lyro and visual automation ecosystem.',
 priceNote:'Monthly Customer Service base prices, up to 10 seats on these tiers. Starter includes 100 handled conversations. Growth starts at $59 and changes with volume. Lyro and Flows allowances are separate; this is not an all-in AI quote.',defaultPlan:1,
 sources:[source('Tidio pricing','https://www.tidio.com/pricing/'),source('Tidio live chat and monthly rates','https://www.tidio.com/live-chat/'),source('Tidio package guide','https://help.tidio.com/hc/en-us/articles/6266099959708-Which-upgrades-do-I-need'),source('Tidio on Lyro capabilities','https://www.tidio.com/blog/lyro-review/')],
 proof:{'live-chat':['Live chat',1],'live-typing':['Live typing preview',1],'visitor-list':['Real-time visitors',1],'automatic-replies':['Lyro AI allowance applies',3],'knowledge':['Lyro trained on your content',3],'human-takeover':['Shared inbox and human support',3],'shared-inbox':['Shared inbox; confirm project setup',3],'translation':['Multilingual Lyro; not the same as two-way operator translation',3],'team-size':['10 seats on the displayed entry tiers',0],'widget-brand':['Customizable live chat',1],'analytics':['Plan-dependent reporting',0]},
 sections:[
 s('Compare the package you will actually use.',`The word Tidio can describe several connected products. Customer Service covers the human support side, Lyro is the AI agent, and Flows provides rule-based automation. Those pieces can work together, but their allowances are not interchangeable. A comparison that takes the cheapest live-chat subscription and treats it as unlimited AI is not helping you budget.

Orka takes a different route through the purchasing decision: select the team size you need, keep unlimited projects under that subscription, and choose managed AI usage or your own provider key. The feature question is still important. Pod and Fleet include capabilities such as message search, image sharing and analytics that should not be silently assigned to Solo. Write down your actual requirements before comparing either free plan with a paid package.`,[2]),
 s('A sensible starting price is not the final bill.',`Tidio’s monthly live-chat page lists Starter at $29 and Growth from $59. Its main pricing page also displays lower monthly equivalents for annual billing. Starter includes 100 handled conversations; Growth scales to higher conversation allowances. The entry plans show ten seats. Orka Pod is also $29, but includes three people; Fleet is $99 with room for twenty. That means the same headline price can represent a very different team and usage arrangement.

If ten people occasionally help with a modest queue, Tidio’s seat allowance is a real advantage worth acknowledging. If several projects grow their support traffic, the conversation allowance deserves more attention. Move the slider, select the appropriate tier and then add the expected automation package. Do not multiply Tidio’s base price by every teammate when the published plan already includes them.`,[0,1]),
 s('Lyro, Flows and Orky solve related jobs.',`Lyro is Tidio’s AI agent trained on your content, with multilingual support and a shared-inbox connection. Flows is its separate automation product. Orky offers automatic answers, editable drafts, summaries and shortcuts, while leaving you the choice of a provider key or managed token billing. A visual rule and a generated response can both be useful; they are simply different ways to decide what happens next.

The initial free Lyro conversations are a trial allowance rather than a promise of a new free bundle every month. Renewing capacity requires the relevant purchase. For Orka, estimate input and output tokens using your actual context and answers. In both cases, try a question with missing information. A useful assistant should make the next step clear rather than confidently completing an answer it does not have. The practical test is the conversation, not just the word AI.`,[2,3]),
 s('Give the help center its own line.',`A public article library is a different feature from a private set of training answers. Orka provides both the public help center and published knowledge for Orky. Your visitors can search articles in the widget, open a branded help site and read translated content. Your team writes in Markdown, reviews automatic translations and sees when updates make another language stale. This is included in every Orka plan.

The Tidio sources reviewed here clearly document knowledge supplied to Lyro. They do not establish an equivalent hosted public help center with custom-domain publishing, collections and the same translation-maintenance workflow. We label that point unverified rather than claiming it is impossible. If self-service publishing is central to your buying decision, ask Tidio to show the customer-facing article site and editor included in your proposed package. Do not confuse Tidio’s own support website with a help center it hosts for your business.`,[3]),
 s('The live-chat basics are not an Orka monopoly.',`Tidio advertises live typing preview and a real-time visitor view. It would be misleading to put a bright Orka checkmark beside those rows and a Tidio cross simply because our own illustrations show them prominently. Both can help a human prepare for the next question. The interface, available context and plan limits determine which version feels useful in your day.

Our suggestion is to test the moment before and after a message. Can your teammate understand what the person is trying to do? Is it obvious which website they are using? Can you leave context for someone else? In Orka, project filtering, visitor attributes, private notes and assignment turn the incoming message into a shared task. Try the same sequence in Tidio. A shorter path through your frequent tasks is more meaningful than the longest list of icons.`,[1]),
 s('A shop and a portfolio of apps need different trials.',`For a shop, use a question about an item, a delivery date and a return exception. Check how much information arrives with the conversation and which actions require another tool. Do not assume that showing an order means the AI can safely alter it. For a portfolio of apps, use three websites with different documentation and ask the same ambiguous question on each. The answer should belong to the right business.

This is where Orka’s project model is particularly worth exploring. You can bring the projects into a shared inbox and keep a clear human owner. At the same time, Tidio’s automation products may fit an existing workflow you do not want to replace. Treat your trial as a rehearsal of the operating day, with a real handover and a real exception, rather than a contest to produce the most polished greeting.`),
 s('Which one would we put on your shortlist?',`Start with Orka if you want a cohesive home for several projects, approachable team pricing and public knowledge that also supports AI. Its working-hours, break-day and panic banners are useful when a small team needs honest expectations. An automated response can cover the routine question while a person handles the exception, without pretending everyone is available around the clock.

Keep Tidio on the shortlist if Lyro and Flows suit the way you already automate support, or if its entry-level seat allowance fits your team particularly well. Ask for the full package price at your expected volume, including recurring AI capacity. The winner for a ten-person team with a quiet inbox may be different from the winner for a solo founder with several busy products. That is a reason to calculate carefully, not a reason to force a universal winner.`)
 ]
},
{
 id:'rocketchat',name:'Rocket.Chat',color:'#FFCEBD',symbol:'↗',theme:'Your support desk. Or your own communications stack.',
 intro:'Rocket.Chat is a communications platform with self-managed deployment and omnichannel tools. Orka is a hosted support workspace. Start with that architectural difference before comparing the buttons.',
 bestOrka:'A hosted website-support workspace that a small team can start using quickly.',bestRival:'Organizations that need self-hosting, deployment control and a broader communications platform.',
 priceNote:'Rocket.Chat’s commercial plans are quote-based. Enter your own monthly license plus hosting estimate. Free self-managed plans have limits and operating costs. An empty estimate is never treated as $0.',defaultPlan:0,
 sources:[source('Rocket.Chat current plans','https://docs.rocket.chat/our-plans'),source('Rocket.Chat commercial offering','https://www.rocket.chat/plans'),source('Handling omnichannel conversations','https://docs.rocket.chat/docs/omnichannel-conversations'),source('Omnichannel Contact Center','https://docs.rocket.chat/v1/docs/omnichannel-contact-center'),source('Livechat widget installation','https://github.com/RocketChat/docs/blob/main/use-rocket.chat/omnichannel/livechat-widget-installation.md')],
 proof:{'live-chat':['Embedded Livechat widget',4],'assignment':['Agent / department transfers and queues',2],'private-notes':['Transfer comments documented; verify your full notes workflow',2],'visitor-profile':['Unified contact profiles',3],'history-search':['Contact-center conversation search',3],'resolved':['Open and closed conversations',3],'saved-replies':['Canned response shortcuts',2],'tags':['Conversation tags',2],'urgency':['Conversation priority',2],'custom-data':['Room and visitor custom fields',2],'sdk':['APIs and integration tools',4],'attachments':['File sharing in the communications platform',0],'read-receipts':['Messaging read receipts',0],'mobile':['Mobile communications clients',0],'team-size':['Free self-managed and paid editions have different limits',0]},
 sections:[
 s('This is partly an architecture decision.',`A website chat widget is only one part of Rocket.Chat’s proposition. The platform serves broader communication needs and offers self-managed deployment. Orka’s current product is a hosted support workspace: website conversations, a shared inbox, visitor context, AI and public help content. These are overlapping tools, but they are not identical categories of software.

If your first requirement is control over where the system runs, start there. A beautifully designed hosted interface cannot replace a deployment requirement. If your first requirement is to answer customers across several websites without operating infrastructure, start with the daily support workflow instead. You will get a clearer decision by stating that priority before comparing features with similar names. A long list of messaging capabilities can hide a fairly fundamental difference in who has to maintain the service.`,[0,1]),
 s('Do not compare today’s product with an old price card.',`Rocket.Chat’s current documentation distinguishes Starter, Community and commercial offerings. Starter is a free self-managed plan for up to fifty users. Community is an open-source edition with its own limitations, including a concurrent-user limit in the current plan guide. The previous Pro plan stopped accepting new purchases in April 2026. Commercial deployment options are quoted rather than represented here by an invented per-seat number.

The calculator therefore asks for your actual license and hosting estimate. Leave it blank if you do not have one; the page will show that a quote is needed. A free license can be a very good choice, but somebody still owns upgrades, backups, monitoring and incident response. Use a realistic internal estimate for that work. Equally, do not inflate infrastructure costs merely to make a hosted competitor look cheaper.`,[0,1]),
 s('Omnichannel support is a real Rocket.Chat capability.',`Rocket.Chat documents visitor conversations that are routed to an agent or offered through a queue. Chats can be transferred to another agent or department, and the contact center provides unified profiles and conversation search. Its Livechat widget can be embedded on a website. It would be wrong to describe Rocket.Chat only as internal team chat and ignore these customer-facing tools.

Orka offers a different daily experience around the shared support inbox. Conversations have owners, tags, private notes and reminders; visitor context and the project sit alongside the message. In a trial, ask two colleagues to exchange a conversation after a complicated answer. Check what follows the handover and what has to be explained again. Then try an unavailable agent, an after-hours message and a returning visitor. These reveal more about your operating fit than a screenshot of either sidebar.`,[2,3,4]),
 s('Public help content deserves a separate check.',`Orka includes a multilingual public help center on every plan. Its articles can appear on your own domain and inside the widget, while supplying knowledge to Orky. Markdown editing, collections, background translation and manual correction give your team a way to maintain the answers in one place. Imports from supported help-center providers can help bring an existing library across.

The Rocket.Chat sources reviewed for this comparison establish communication, deployment and omnichannel capabilities. They do not establish the same included, hosted public article-publishing workflow. That row is marked unverified rather than being treated as an automatic absence. If you already operate documentation elsewhere, that separation may be perfectly acceptable. Ask how visitors search it, how agents share it and how any AI receives current knowledge. The cost of maintaining two sources of truth is an operational question, not merely another subscription line.`,[0,3]),
 s('Deployment control can be the deciding advantage.',`Rocket.Chat’s commercial positioning includes private-cloud, on-premises and more isolated deployment options. That can matter to organizations with a defined infrastructure policy. Its current plan guide also describes capabilities such as identity integration and administrative controls. Those should be evaluated against the exact edition and contract you are considering, rather than generalized to every free installation.

Orka does not publish an equivalent self-hosted deployment in its current feature catalogue. Nor does this comparison claim that a small-team support product automatically satisfies your organization’s retention, identity or regulated-data requirements. If those are non-negotiable, get written answers before migrating. The right conclusion may be that Rocket.Chat is the better architectural fit even when Orka is the more attractive support interface for a simpler business.`,[0,1]),
 s('Run a trial with the people who will own it.',`Invite both a support teammate and the person responsible for the system. The support teammate should test replying, searching, transferring and picking up a conversation on another device. The technical owner should test installation, updates, authentication and recovery. If one person is doing both jobs, record the time spent on each. A free plan can be economical while still consuming time you would rather spend elsewhere.

For Orka, use that same time to configure the projects, publish the first articles and set realistic availability. Test an AI draft against your actual documentation, then pass a difficult question to a human. The comparison should include readiness for ordinary work, not just successful installation. A system that starts cleanly but never gets its documentation or handover rules finished is not yet solving the support problem.`),
 s('Choose the responsibility you actually want.',`Orka is worth a close look when you want to operate customer support, rather than operate the software infrastructure behind it. The unlimited-project model and team tiers make sense for founders, agencies and small businesses who need a shared place to help people. The free help center is part of that setup, not an extra publishing product to stitch in later.

Rocket.Chat belongs on the shortlist when communications and infrastructure control are central requirements. Its omnichannel capabilities mean that customer support can be part of that wider environment. You do not have to pretend the products are identical to compare them fairly. Decide which responsibilities you want to keep, what your team is equipped to manage, and where you need a vendor to take care of the system for you.`)
 ]
},
{
 id:'crisp',name:'Crisp',color:'#C5CEFF',symbol:'◡',theme:'Two thoughtful inboxes. Different trade-offs.',
 intro:'Crisp is a close alternative, with workspace pricing, a shared inbox and a real knowledge base. Orka adds its own take on multi-project support, free self-service and human boundaries.',
 bestOrka:'Free multilingual help, unlimited projects and the choice to bring an AI key.',bestRival:'A broad workspace with visual workflows, channels and mature help-content tools.',
 priceNote:'Monthly prices per workspace, not per agent. Seats included: Free 2, Mini 4, Essentials 10, Plus 20. Extra Plus seats are $10 each. AI credits, allowances and channel costs must be reviewed separately.',defaultPlan:2,
 sources:[source('Crisp pricing','https://crisp.chat/en/pricing/'),source('Knowledge Base quickstart','https://help.crisp.chat/en/article/getting-started-with-the-crisp-knowledge-base-i2tsm1/'),source('Crisp workflows','https://help.crisp.chat/en/article/understanding-and-mastering-the-crisp-workflows-1boypme/'),source('Crisp Inbox documentation','https://help.crisp.chat/en/category/inbox-15ctwet/')],
 proof:{'live-chat':['Live chat',0],'shared-inbox':['Shared workspace inbox',3],'email-follow-up':['Email in the inbox',3],'team-size':['Workspace seat bundles',0],'knowledge':['Help articles support Hugo',1],'automatic-replies':['AI agent and workflow options',2],'help-center':['Essentials and Plus',1],'multilingual-help':['Multiple languages; manual article localization documented',1],'help-domain':['Custom domain or crisp.help',1],'help-markdown':['Markdown editor',1],'help-collections':['Article categories',1],'help-ai':['Knowledge for Hugo',1],'help-branding':['Brand customization',1],'help-publishing':['Draft and publish workflow',1],'sdk':['SDK / integrations',0],'mobile':['Mobile apps',0],'remove-branding':['Plan-dependent white labeling',0],'custom-data':['Variables and custom data in workflows',2]},
 sections:[
 s('This is a comparison of two plausible choices.',`Crisp is not a straw-man enterprise product placed beside a friendly startup. It has workspace pricing, a shared inbox and a public knowledge base. A small business can reasonably put both Crisp and Orka on its shortlist. The useful question is where the included features, team bundles and working style diverge, not whether one has discovered customer support and the other has not.

Orka emphasizes unlimited projects in one subscription, a free multilingual help center and an AI teammate you can keep in draft mode or allow to answer. Crisp offers its own integrated workspace and automation tools. If your existing support process already feels natural in Crisp, that familiarity is worth something. A move should solve a concrete problem such as plan access, project organization or the way your team maintains knowledge.`,[0,3]),
 s('Workspace pricing makes this less obvious than it looks.',`Crisp lists Free for two seats, Mini at $45 for four, Essentials at $95 for ten and Plus at $295 for twenty. These are workspace prices, not amounts to multiply by every agent. Orka offers Solo free for one, Pod at $29 for three and Fleet at $99 for twenty. A ten-person team can therefore see a lower base price on Crisp Essentials than on Orka Fleet. A twenty-person comparison produces a different result.

This is why the calculator lets you choose a Crisp plan instead of announcing an automatic winner. Essentials includes the knowledge base, while other capabilities and AI allowances vary by package. Compare the plan you would really buy. If you need several separately billed workspaces, enter that into your own budget too; our displayed calculation deliberately covers one Crisp workspace and does not guess your organizational structure.`,[0]),
 s('Both products understand Markdown and self-service.',`Crisp’s knowledge base supports Markdown, categories, multiple languages, custom domains and content for Hugo. Orka also uses Markdown and supports branded public help, collections and widget access. Calling Markdown an Orka-only advantage would be false. The meaningful difference is that Orka includes its help center on the free plan, while Crisp’s published documentation places the knowledge base on Essentials and Plus.

Translation maintenance is another detail to inspect. The Crisp quickstart describes adding languages and manually localizing articles. Orka includes background automatic translation with editable results and outdated markers after source changes. For either system, check a real article in a language you serve. The words should be correct, the links should still work, and the visitor should reach a useful answer without discovering half-translated navigation along the way.`,[1]),
 s('Automation can be worth paying for.',`Crisp documents a workflow builder with conditions, message steps, internal actions and AI actions. That is a meaningful tool when your team wants a deliberately structured process. It can express decisions about visitor information and route the interaction through steps. Orka’s current catalogue establishes automatic replies, drafts, summaries, shortcuts and human takeover; it does not establish a directly equivalent general-purpose visual workflow builder.

Think about whether you need a conversation assistant or an explicit automation design. For a routine product question, a reviewed answer from current documentation may be enough. For a sequence involving several conditions and updates, a visual workflow may be the reason you buy a platform. Test the hardest branch in your process, including the unhappy path, before deciding that a simpler interface can replace it.`,[2]),
 s('AI credits are not the same as model tokens.',`Crisp packages include stated AI credits at different levels. Orka separates team subscription pricing from model-specific AI usage and offers a bring-your-own-key option without markup. Neither arrangement can be translated into a universal number of useful answers without assumptions about the workload. A vendor’s illustrative answer count is not a promise that your longest conversations will fit the same average.

Keep two measurements during a trial: what you spend and how often a person has to repair the answer. A cheap draft that needs three corrections is not necessarily efficient. A more expensive response that handles a difficult question cleanly can be worthwhile. For Orka, the pricing page names the models and separates input from output. Use that calculation as a budgeting aid and bring your actual context lengths into it.`,[0]),
 s('The small details can decide the daily experience.',`Orka gives a teammate context before and during the conversation: the current project, visitor information, recent activity and cart details when connected. Private notes and mentions help another person join without asking the customer to repeat everything. Availability and night, break-day or panic banners explain the human side of response times. These are especially useful when the support team is also building or running the business.

Crisp has a substantial inbox of its own, so a trial should compare the same sequence on both sides. Search for an earlier exchange, involve a colleague, find a help article and continue the conversation. Then ask the person who uses the inbox least often to repeat it. The system that makes occasional contributors comfortable may be more valuable than the one that only your power user navigates quickly.`,[3]),
 s('Our verdict depends on the team size and workflow.',`Orka makes a strong case for a founder or a small crew managing several projects, especially if public documentation and multilingual support should be available from day one. Pod is an approachable step up, and Fleet leaves room for a larger crew without adding a seat charge for each person within its twenty-person allowance. The option to use your own AI key also deserves a place in the comparison.

Crisp remains compelling when its ten-seat Essentials bundle fits neatly or when its broader automation and workspace tools match an established process. There is no need to invent a deficiency to recommend Orka for a different situation. Try both with one normal question, one ambiguous question and one exception. Then choose the workspace that makes those three conversations clearer for the people on both sides.`)
 ]
},
{
 id:'chatra',name:'Chatra',color:'#F9DE9D',symbol:'☷',theme:'The human conversation comes first.',
 intro:'Chatra keeps live messaging approachable. Orka adds a multi-project support workspace, a public help center and Orky. The question is how much you want around the conversation.',
 bestOrka:'A shared home for several projects, public documentation and AI assistance.',bestRival:'Teams that primarily want straightforward human messaging and Chatra’s existing workflow.',
 priceNote:'Monthly Essential and Pro prices are per agent. Annual equivalents are $25 and $33. The current free plan lists one agent and five chats per month. Annual discounts and taxes are excluded.',defaultPlan:1,
 sources:[source('Chatra current plans','https://chatra.com/plans/'),source('Chatra operator and chatbot documentation','https://chatra.com/help/'),source('Chatra asynchronous messenger','https://chatra.com/messenger/')],
 proof:{'live-chat':['Live messaging',2],'live-typing':['Typing insights',1],'read-receipts':['Read receipts',1],'visitor-profile':['Visitor context',1],'browsing-context':['Page and device context',1],'email-follow-up':['Replies can continue by email',2],'assignment':['Agent groups and routing',1],'mobile':['Mobile messaging apps',2],'saved-replies':['Saved replies in operator tools',1],'team-size':['Paid subscriptions per agent',0]},
 sections:[
 s('Start with the conversation you need to support.',`Some teams need a customer-service platform with many connected pieces. Others need an approachable way to answer people visiting a website. Chatra is relevant to that second situation. Its messenger is designed to support live and asynchronous exchanges, including following up when a visitor is no longer on the page. Orka covers website conversations too, but places them inside a broader project, knowledge and AI workflow.

Imagine a small business that gets a few product questions each day. The most valuable feature may be the confidence that somebody will see and answer them. Now imagine the same team adding three websites, a translated article library and a person covering evenings. The questions change: which project is this, where is the correct answer, and who should take over? That is the point at which the surrounding workspace deserves as much attention as the chat bubble.`,[2]),
 s('Use the current free-plan limit.',`Chatra’s current plans page lists a free option for one agent with five chats per month. Essential is $31 per agent monthly, and Pro is $41. Annual billing lowers the displayed equivalents to $25 and $33. Older descriptions of the free product should not override the current plan table when you prepare a budget. The calculator on this page uses the monthly figures.

For three paid Essential agents, the base calculation is $93 a month. Orka Pod is $29 for up to three people, with unlimited projects. That difference is useful to see, but it is not a complete migration argument. List the particular Chatra functions you use, check which Orka plan contains the replacement, and include the time it takes to change your setup. A feature your team depends on can be worth more than a modest subscription difference.`,[0]),
 s('Live typing and asynchronous replies are shared ground.',`Chatra documents typing insights, read receipts, visitor context and operator tools. These are not capabilities unique to Orka. They can make human support feel attentive: the agent can prepare, the visitor can see the conversation progressing, and the next reply does not need to start from nothing. Chatra’s asynchronous messenger also acknowledges that people leave a page before a response arrives.

Orka combines the same general support needs with assignment, private notes, tags, reminders and project filters. Try a returning visitor during your trial. Ask a colleague who did not handle the first question to find the context and write the next reply. The goal is not simply speed. It is to avoid a fast answer that belongs to the wrong person or the wrong project. A few well-placed details can make that distinction obvious.`,[1,2]),
 s('A chatbot label does not establish the same AI.',`Chatra’s documentation describes rule-based chatbot paths and visitor prompts. That can be a perfectly useful way to collect information or direct someone to the right next step. It should not be treated as evidence of the same document-grounded generative assistant, token billing or provider-key choices that Orka offers. Conversely, a generative answer is not automatically better than a clear, deterministic question.

Orky can propose a draft for review, answer automatically from your knowledge, summarize and help with everyday writing shortcuts. A person can take over, and the team can decide when the assistant participates. In your evaluation, choose one question that has a precise policy answer and one that requires a personal decision. Check whether the tool gives a reliable next step in each case. Avoid awarding points merely because one product uses the word AI more prominently.`,[1]),
 s('The help center is a distinct reason to consider Orka.',`Orka includes a public help center, custom-domain publishing and a searchable Help tab in the widget. Articles written in Markdown can be arranged into collections and sections. Automatic translations are editable, and the original and translated content can be maintained together. Published articles also supply knowledge to Orky, so writing one useful answer can help both the person searching and the assistant replying.

An equivalent public help-center publishing product was not verified in the Chatra sources reviewed here. That is an evidence boundary, not a claim that no integration or separate documentation tool could meet the need. If you already have an excellent article site, ask whether you want to keep it. If you do not, estimate the work of creating and maintaining one elsewhere. The answer should be part of the comparison rather than hidden behind the generic phrase customer support.`,[1,2]),
 s('Set expectations without pretending to be a large team.',`A small team often needs a helpful way to be unavailable. Orka’s online and away indicators, reply-time expectations and night, break-day and panic banners are designed around that reality. The visitor should know what happens next, while the team gets enough room to do the rest of its work. An automatic answer can help with a documented question without claiming a human is online.

For any messenger, test what a new visitor sees at the end of the day. Send a message, close the browser and come back later. Then check the experience from a phone. This is a more representative test than keeping the agent and visitor windows open side by side all afternoon. People use support around their own lives, and the product should make that ordinary interruption understandable.`),
 s('Choose the scope that fits your next stage.',`Keep Chatra in consideration if your team values its existing messaging experience and does not need to reorganize support around AI and a public knowledge library. Familiarity and a focused workflow are real benefits. A system that people reliably use is more useful than an ambitious replacement that nobody finishes configuring.

Choose Orka when the conversation increasingly depends on several projects, shared context and answers that should be published once and reused. Start with one project, a few accurate articles and reviewed AI drafts. Add automatic replies only where you are comfortable with the knowledge and handoff. There is no need to turn every feature on immediately. A careful transition lets you judge whether the broader workspace is making support clearer rather than simply adding another set of settings.`)
 ]
},
{
 id:'willdesk',name:'WillDesk',color:'#FFD4AB',symbol:'▤',theme:'A store-first helpdesk. A multi-project alternative.',
 intro:'WillDesk is built around ecommerce support. Orka brings websites and projects into one inbox with a free multilingual help center. Compare store depth, conversation allowances and the actual work your team does.',
 bestOrka:'Mixed projects, a shared team and knowledge that works beyond one storefront.',bestRival:'Shopify-centered support with order tracking, store integrations and unlimited agents.',
 priceNote:'Prices and allowances from WillDesk’s developer-maintained Shopify listing. Recurring Shopify charges use 30-day billing cycles. Unlimited agents; store and conversation limits vary. AI, tracking and conversation overages are excluded.',defaultPlan:1,
 sources:[source('WillDesk on the Shopify App Store','https://apps.shopify.com/self-faq'),source('WillDesk official plan features','https://www.willdesk.com/price/'),source('WillDesk product','https://www.willdesk.com/')],
 proof:{'live-chat':['Live chat and helpdesk',0],'email-follow-up':['Email support',0],'shared-inbox':['Multichannel / store support; store limits apply',0],'team-size':['Unlimited agents',0],'saved-replies':['Macros',0],'knowledge':['AI knowledge learning',0],'automatic-replies':['AI conversations; allowance / overage applies',0],'help-center':['Help center available',0],'help-domain':['Custom FAQ domain on Basic and above',0],'tags':['Conversation tagging',1],'analytics':['Plan-dependent reports',1]},
 sections:[
 s('Begin with whether the store is the whole business.',`For a Shopify merchant, much of support revolves around a purchase: the product, the shipment, the order and the exception. WillDesk’s product and listing emphasize those ecommerce jobs. That focus can save time when nearly every incoming message needs store information. Orka’s wider project model is particularly relevant when the team supports a store alongside an app, a service website or several unrelated products.

Consider the support queue you actually have. If almost every question asks where an order is, depth in order tracking may matter more than a broad project view. If the queue moves between subscriptions, bookings, products and account access, bringing those projects together may be more useful. Neither decision is about having the most features in the abstract. It is about putting the information for your frequent questions in the right place.`,[0,2]),
 s('Unlimited agents are a real WillDesk advantage.',`The developer’s Shopify listing describes unlimited agents, including on the free option. Free includes one store and twenty conversations. Basic is $16.90 per billing cycle with three stores and one hundred conversations; Pro is $89.90 with a higher conversation allowance and multistore features. The listing also publishes separate overages for conversations, order tracking and AI. Shopify recurring charges use thirty-day cycles, so we label that billing basis explicitly.

Orka chooses team tiers instead: one person free, three for $29 monthly and twenty for $99 monthly, with unlimited projects. A larger team handling a small number of store questions may find WillDesk’s structure attractive. A smaller team spanning many projects should examine the other direction. The calculator does not multiply WillDesk by your agent count, and it does not hide the fact that the base allowance is only one part of the likely invoice.`,[0]),
 s('A free help center is not exclusive to Orka.',`WillDesk lists a help center among its features, and its paid Basic offer includes a custom FAQ domain. It would be inaccurate to describe the choice as Orka having documentation and WillDesk having none. Public answers can be valuable in both products, especially when order and delivery questions repeat. Check which presentation and domain options are included in the exact plan you would use.

Orka’s help center includes Markdown editing, collections and sections, a branded domain, widget search and published knowledge for Orky. It also includes automatic translations that can be manually corrected, with outdated markers when the source changes. For a multilingual team, that maintenance workflow deserves a practical test. Change a sentence in a real policy and inspect what happens in every language. The easy first translation is only half of the documentation job.`,[0,1]),
 s('Look carefully at ecommerce actions.',`WillDesk’s offering includes order tracking and store-oriented integrations. Those are meaningful advantages for a support team answering purchase questions. Orka can show cart and visitor context when connected, but that should not be presented as the same thing as a complete order-management workflow. Seeing what someone is looking at and safely changing a transaction are different capabilities.

During a trial, use three tasks: find an order, explain its status and request an exception. Record which tasks happen inside the helpdesk, which open another system and which require a person with additional permissions. Ask for a demonstration of any action you expect an AI to perform. A fluent explanation of a refund policy is not proof that the software can issue a refund correctly. Your test should distinguish information, recommendation and execution.`,[0,2]),
 s('Build an AI budget from the published unit.',`WillDesk’s listing charges for AI conversations beyond the included allowance, while Orka uses model-specific input and output tokens for managed AI. Those units cannot be compared by simply placing two small dollar figures beside each other. Ask how a conversation is counted, what happens when the visitor returns and whether an unsuccessful automated exchange consumes the allowance.

For Orka, include the prompt, supplied knowledge and conversation history in input usage; output is the generated response and any other billable model output. The separate calculator gives a transparent estimate using the named model rates. Bring-your-own-key users pay their provider directly without an Orka margin. Whatever option you choose, test on a realistic sample containing long questions, follow-ups and cases that need a human, rather than only short greetings.`,[0]),
 s('Keep the team’s handoff in the picture.',`Price and store data matter, but a customer usually notices whether the next person understands the problem. Orka’s shared inbox provides assignment, private notes, tags, reminders and project filters. An agent can use a reviewed draft and pass the conversation on with the relevant context. The help center can carry the standard policy while the teammate handles the exception.

For your WillDesk trial, repeat the same scenario with two agents and a returning customer. Check how the conversation is found, what the second agent sees and whether the first reply promised something the store cannot provide. Also test what happens outside your staffed hours. Clear expectations and a reliable handoff can prevent the team from creating additional work through an answer that was fast but incomplete.`),
 s('Our recommendation: follow the center of gravity.',`Choose WillDesk if Shopify operations are the center of your support day and its order tools, store integrations and unlimited-agent structure match your workload. Include the expected conversation, AI and tracking overages before comparing totals. A low entry price can still be a strong value when the allowance fits; it simply should not be mistaken for unlimited everything.

Choose Orka if your team needs a consistent support home across different projects, with public multilingual knowledge and AI that can remain under human review. The unlimited-project model removes one source of friction as the business branches into new websites. If you are moving an established store, keep your order-management process intact until the replacement has proved itself. A support migration should make the customer’s next question easier, not interrupt the tools that already answer it.`)
 ]
},
{
 id:'chatway',name:'Chatway',color:'#C2E8DD',symbol:'↩',theme:'A familiar chat. A closer comparison.',
 intro:'Chatway offers live chat, commerce context, AI and a help center on selected plans. Orka brings its own blend of project support, editable knowledge and token-based AI. Both deserve a proper trial.',
 bestOrka:'Unlimited projects and a multilingual public help center from the free plan.',bestRival:'Teams wanting Chatway’s connected channels and store integrations.',
 priceNote:'Monthly plans: Solo $29 / 1 seat, Team $79 / 4 seats, Plus $149 / 10 seats. Additional paid-plan seats are $19 monthly. Help center starts on Team. AI resolutions and other usage are excluded.',defaultPlan:2,
 sources:[source('Chatway pricing','https://chatway.app/pricing'),source('Chatway Help Center product','https://chatway.app/help-center'),source('Setting up a Chatway help center','https://chatway.app/help/getting-started/how-to-set-up-a-help-center-or-knowledge-base-in-chatway')],
 proof:{'live-chat':['Live chat',0],'shared-inbox':['Multiple widgets / inboxes on Plus',0],'visitor-cart':['Store order and cart context',0],'translation':['Live translation on paid plans',0],'automatic-replies':['AI resolution add-on',0],'help-center':['Team and Plus',0],'help-domain':['Help center custom domain',1],'help-widget':['Help content connected to live chat',1],'help-branding':['Help center appearance settings',2],'help-collections':['Organized articles and categories',2],'remove-branding':['Paid plans',0],'team-size':['Seat bundles plus additional seats',0]},
 sections:[
 s('The overlap is substantial.',`Chatway and Orka both belong on a shortlist for website support. Chatway combines live chat with connected channels, store context and an AI option. It also offers a help center on selected plans. Orka combines a shared project inbox, public knowledge, visitor context and an AI teammate. A useful comparison therefore needs more detail than saying one is a modern chat widget and the other is not.

Start by writing down which channels produce your actual support work. Then separate the human team requirement from the automation requirement. A business with four agents answering website and social questions is buying a different setup from a founder supporting five small products. Your plan choice should follow that shape rather than the plan name that sounds closest to your business size.`,[0]),
 s('The seat bundles deserve a proper calculation.',`Chatway’s monthly plans list Solo at $29 with one agent, Team at $79 with four and Plus at $149 with ten. Additional seats on paid plans are $19 monthly. Annual commitments offer lower equivalents. The calculator uses the monthly plans and the stated extra-seat price. Orka Pod is $29 for three people, and Fleet is $99 for up to twenty.

For a team of four, compare Orka Fleet with Chatway Team, not automatically with Chatway Plus. For a team that needs multiple inboxes or help centers, check the higher-plan features too. This is a good example of why the lowest seat-adjusted number is only a starting point. The appropriate plan depends on both who answers and what workspace organization they need. Taxes, AI and other usage are outside the base subscription figures displayed here.`,[0]),
 s('Both can publish answers before someone asks.',`Chatway’s help center supports a branded article site and can connect help content with the chat experience. Its documentation describes article creation, appearance settings and ways to organize knowledge. The pricing page places the help center on Team and Plus. Those are real self-service features, and they belong in the comparison rather than being omitted to make Orka look stronger.

Orka includes the help center on every plan, including Solo. You can use your own domain, write Markdown, group articles into collections and sections, and expose a searchable Help tab inside the widget. Automatic translation, manual corrections and outdated markers make the ongoing language work visible. Published articles also support Orky. If documentation is your first priority and the human team is still one person, the difference in entry point may matter more than the larger-team price.`,[0,1,2]),
 s('Commerce context can change which inbox feels complete.',`Chatway’s paid offerings describe Shopify and WooCommerce connections, including order and cart context. If those are the systems your team uses all day, test them directly. Useful commerce information can prevent an agent from asking for details the business already has. Orka also presents visitor and cart context when connected, but the current catalogue is not evidence of every store integration or transactional action you might need.

Use a real customer scenario with a cart change, a previous purchase and a question about a policy exception. See which information is available without asking the customer again. Then ask whether the agent can act on that information or only view it. A support tool can be excellent at conversation while still relying on the store’s own admin for certain changes. That is fine when it is understood before you commit.`,[0]),
 s('Do not turn a resolution into a made-up token count.',`Chatway lists AI at $0.50 per resolved conversation, with a small free trial allowance. Orka’s managed AI is billed using named model token rates with a two-times multiplier, or you can use your own provider key without markup. These are different pricing structures. A resolved conversation may involve several generated replies, while token usage depends on both the context and the outputs.

Test a realistic sample and note the billing definition alongside the result. Does a handoff count? Does a returning question begin a new unit? How much context did the model need? The answers to those questions are more useful than assuming every conversation contains the same number of tokens. Our calculator keeps the base team subscription separate from Orka’s token estimate so you can see exactly which part of the budget you are changing.`,[0]),
 s('Human review is a product choice, not a failure of automation.',`Orka lets the team use an AI draft without sending it immediately. That is useful while you establish the tone, improve documentation or handle a situation where a person must decide. Automatic replies and human takeover are separate parts of the workflow. Private notes, mentions, assignment and reminders keep the people coordinated after the assistant has done its part.

Try the same workflow in your Chatway evaluation. Ask one agent to review a draft and another to take over an automated exchange. The ideal setup makes it obvious what has been sent and what is still a suggestion. A team should not need to guess whether a line in the composer is a published promise. The quieter details of the interface can be more important than the sophistication of the first AI response.`),
 s('Choose for your channel mix and your knowledge workflow.',`Orka is a strong candidate when one shared crew supports several projects and wants public knowledge available from the start. The team tiers, free multilingual help center and provider-key choice give you a practical basis for growing gradually. You can start with a human answer, use drafts as assistance and only automate the questions your knowledge can reliably cover.

Chatway deserves consideration when its store integrations, channel connections and plan organization fit the business you already run. Its help center is part of the offering, so the question is where that plan begins and whether its workflow suits the team. Use the calculator to narrow the financial comparison, then ask the people who will answer messages to test both. Their ability to find context and finish a conversation is the outcome that matters.`)
 ]
},
{
 id:'gorgias',name:'Gorgias',color:'#F9C9BD',symbol:'◈',theme:'Commerce depth. Or room for every project.',
 intro:'Gorgias goes deep into ecommerce support and AI actions. Orka focuses on approachable support across projects. The fair comparison includes what happens to an order, not just what appears in the inbox.',
 bestOrka:'A small team supporting several kinds of websites and products.',bestRival:'Commerce teams needing deep Shopify workflows and automated order actions.',
 priceNote:'Gorgias pricing depends on ticket volume and AI usage. Enter your actual helpdesk quote; this calculator does not invent a universal base price. AI, voice, SMS, overages and taxes are excluded.',defaultPlan:0,
 sources:[source('Gorgias pricing','https://www.gorgias.com/pricing'),source('How Gorgias bills usage','https://helpcenter.gorgias.com/en-US/how-youre-billed-for-using-gorgias-199385'),source('Gorgias AI Agent explained','https://helpcenter.gorgias.com/en-US/ai-agent-explained-497772'),source('AI Agent on Chat requirements','https://helpcenter.gorgias.com/en-US/set-up-and-use-ai-agent-on-chat-828220'),source('Gorgias help-center articles','https://helpcenter.gorgias.com/en-US/ai-generated-help-center-articles-422031')],
 proof:{'live-chat':['Live chat and helpdesk',0],'email-follow-up':['Email support',2],'knowledge':['Help center, website and connected knowledge',2],'automatic-replies':['AI Agent with configured actions',2],'human-takeover':['AI handover to agents',2],'translation':['Multilingual AI support; verify operator translation separately',2],'help-center':['Public help center',4],'multilingual-help':['Multilingual help content',4],'help-domain':['Branded help-center publishing options',4],'help-collections':['Categories and subcategories',4],'help-publishing':['Draft review and publishing',4],'help-ai':['Help content supports AI Agent',2],'visitor-profile':['Connected commerce context',2],'analytics':['Helpdesk reporting',0]},
 sections:[
 s('The strongest reason to choose Gorgias is worth stating.',`Gorgias is built around ecommerce, with an AI agent that can use store information and configured actions. Its documentation describes shopping and support tasks, including order-related changes and escalation. For a merchant, that depth can matter more than the design of the chat window. A support interaction often ends only when something in the store has changed.

Orka’s current catalogue establishes visitor and cart context, a shared inbox, help content and AI replies. It does not establish equivalent automatic refunds, subscription changes or order cancellations. We will not turn a cart illustration into a claim that those actions exist. If transactional automation is the central reason you are buying, Gorgias should remain a serious candidate. If your team supports several kinds of websites, a broader project workspace may be the more natural starting point.`,[2]),
 s('A price-per-agent comparison would miss the model.',`Gorgias organizes its pricing around ticket volume and AI usage rather than simply multiplying a monthly agent price. A ticket becomes billable under the conditions in its billing documentation, including replies generated through automation. The current billing guide distinguishes helpdesk ticket charges from AI automation charges and explains situations in which both can apply. That definition matters when estimating the invoice.

Instead of publishing a guessed base price, our calculator accepts the helpdesk amount from your actual Gorgias offer. It then compares that amount with the Orka team tier for the selected number of people. AI and other usage stay outside that calculation. This is deliberately a base-budget comparison, not a claim that the software does the same work. If you do not have a quote, the result says so rather than treating a missing number as free.`,[0,1]),
 s('Help centers are part of both products.',`Gorgias has a public help-center workflow with articles, categories, publishing and multilingual content. It can also suggest article drafts from support interactions, which can be useful when your knowledge is scattered through a large history of tickets. Those drafts still deserve review before customers rely on them. The existence of that feature is a meaningful difference from merely providing a blank editor.

Orka’s help center is included on every plan and combines Markdown writing, collections, sections, custom-domain publishing and widget search. Automatic translations can be corrected by hand and marked outdated when source content changes. Published articles help Orky as well as visitors. The current Orka catalogue does not establish Gorgias-style article discovery from historical tickets, so we do not claim it. Compare how you will create the first useful library and how you will maintain it six months later.`,[4]),
 s('Check the exact commerce platform and channel.',`Gorgias’s AI-on-Chat guide specifies Shopify requirements for that particular setup. Its broader AI documentation discusses channels and connected commerce knowledge, but that does not mean every feature is available on every ecommerce platform in exactly the same way. A general integration logo is not proof of a specific action. Check the workflow, permissions and channel you intend to deploy.

This is equally important for Orka. An SDK and custom attributes let you connect context, but they do not magically create a finished integration for every store or internal tool. Ask what arrives automatically, what must be configured and what needs custom work. During a trial, distinguish a displayed order detail from a verified customer identity and an authorized change. Each is a separate step in a trustworthy support process.`,[2,3]),
 s('An AI answer and an AI action need different tests.',`For an answer, you can compare the response with a published policy. For an action, you need to inspect the changed record and the permissions that allowed it. Gorgias’s documented commerce actions make the second test relevant. Use a safe test order and an edge case such as an item already being prepared for dispatch. Check whether the system hands over when the exception requires a person.

In Orka, test the strengths that are actually established: knowledge-based replies, drafts you review, summaries, quick writing assistance and human takeover. Ask the assistant to explain the policy, then ask for an exception. A good support workflow should make the limit clear and keep the context for a teammate. Do not reward a model for sounding certain about an operation the product has not demonstrated it can perform.`,[2]),
 s('Several projects can change what matters most.',`A business may run a Shopify store, a booking service and a software product with the same small crew. Orka’s unlimited-project model is designed for that kind of shared attention. Project filters, visitor attributes, private notes and assignment help the team carry context without mixing the businesses. The free help center gives each knowledge workflow a place in the support setup.

A store-led organization may reasonably prefer a product that goes further into commerce rather than one that treats several types of project consistently. Map your last fifty support questions to the action needed to finish them. If most require store changes, test those deeply. If many concern different apps, accounts or services, test how quickly the team switches context. That small exercise can reveal the right product category before a detailed feature comparison begins.`),
 s('Our verdict does not depend on pretending Orka does everything.',`Orka is a compelling option for founders and small teams who want live support, public knowledge and AI assistance across several projects. Its team pricing is easy to understand within the published seat limits, and the choice of managed tokens or your own provider key gives you control over the AI payment model. The interface is built around people collaborating on conversations.

Gorgias can be the better fit when ecommerce operations and automated store actions are the job you need done. Compare the full ticket and AI budget against the work those actions remove, and verify the requirements for your platform. A higher subscription can be justified by useful operational depth. A lower subscription can be a better decision when you do not need that depth. The right answer follows your support workload, not a forced winner badge.`)
 ]
},
{
 id:'tawk',name:'tawk.to',color:'#BFE5B1',symbol:'◌',theme:'Free is a very good starting point.',
 intro:'tawk.to offers a genuinely free core support product. Orka also starts free, with a different team model and knowledge workflow. Here is the comparison without pretending that every rival is expensive.',
 bestOrka:'Multi-project support with Orky, editable multilingual knowledge and clear team tiers.',bestRival:'Teams prioritizing a free core live-chat and knowledge-base product.',
 priceNote:'Core tawk.to is free without a per-agent subscription. The optional monthly Remove Branding add-on is $29. AI Assist, hired agents and other services are separate; a free AI tier has limits.',defaultPlan:0,
 sources:[source('Why tawk.to is free','https://www.tawk.to/why-free/'),source('tawk.to add-ons','https://www.tawk.to/add-ons/'),source('tawk.to setup and knowledge-base guide','https://help.tawk.to/article/a-checklist-to-help-you-set-up-your-tawkto-dashboard'),source('AI Assist billing','https://help.tawk.to/article/how-to-manage-billing-for-ai-assist'),source('Knowledge Base categories','https://help.tawk.to/article/creating-knowledge-base-categories')],
 proof:{'live-chat':['Free core live chat',0],'team-size':['No per-agent core subscription',0],'help-center':['Knowledge Base',2],'help-widget':['Knowledge Base in the widget',2],'help-domain':['Custom domain with paid branding add-on',1],'help-collections':['Categories and subcategories',4],'knowledge':['AI Assist uses your sources',2],'automatic-replies':['AI Assist; free and paid quotas',3],'mobile':['iOS and Android apps',2],'saved-replies':['Shortcuts',2],'widget-brand':['Widget customization',2],'online-away':['Online, away and offline states',2],'remove-branding':['Paid add-on',1]},
 sections:[
 s('Let us say the important part first: the core is free.',`tawk.to describes its core live-chat product as free, without turning each agent into a recurring seat subscription. That is a meaningful advantage, especially for a team with many occasional contributors and a limited budget. It would be dishonest to construct a comparison that gives tawk.to an invented paid base plan or ignores the free offering.

Orka also has a free plan, but Solo is for one person. Pod is $29 monthly for three people and Fleet is $99 for twenty. If the question is only which base product charges less for a larger human team, tawk.to may have a straightforward answer. The reason to consider Orka is the fit of its project, knowledge and AI workflow, not a claim that every alternative costs more. Begin the trial with that distinction clear.`,[0]),
 s('Free core and optional services are separate decisions.',`tawk.to offers paid extras, including AI Assist and removal of its branding. Its add-on page lists monthly Remove Branding at $29 and connects that option to branded help-center use. AI Assist has a free tier with limits and paid capacity. Optional human staffing and other services should be evaluated on their own terms, not quietly added to every user’s hypothetical invoice.

The calculator therefore lets you compare the free core or the optional branding package. It does not assume that your business needs every add-on. For Orka, team subscription and AI usage are also separate lines. Compare the configuration you would use in production, including whether you care about branding, how many people answer and whether automated replies are actually part of your plan. A free tool can remain a good choice even after you buy a useful extra.`,[1,3]),
 s('tawk.to has a knowledge base, too.',`The tawk.to setup guide describes a public Knowledge Base and its integration into the chat widget. Visitors can find an answer before starting a conversation. Its documentation also explains categories and nested subcategories. These are real self-service capabilities, and they mean that a help center is not an Orka-only feature in this comparison.

Orka includes a help center with custom-domain publishing, Markdown articles, collections and sections, automatic translations and manual correction. The translation workflow marks content outdated when the source changes, and published articles support Orky. The practical difference to explore is how you create and maintain your particular library. Take an existing policy, translate it, revise it and find it from the widget. That sequence is more informative than asking whether each product can display a list of articles.`,[2,4]),
 s('AI limits should be compared in their own units.',`tawk.to AI Assist uses its own message-credit and knowledge allowances. Its billing guide explains the difference between the free and paid options. Orka’s managed AI uses separate input and output token rates for the named model, with a two-times multiplier on the standard provider rate. Bring-your-own-key users pay their provider directly without an Orka markup.

A message credit is not automatically one thousand tokens, just as a long support conversation is not a fixed-size document. We do not translate between those units by guessing. Use the same sample of customer questions in both products and inspect the consumption alongside answer quality. Include a multi-message problem, a question requiring a long article and a situation that needs a human. The budget should reflect the work you expect the assistant to handle.`,[3]),
 s('The reason to pay should be visible in the workflow.',`In Orka, the project, the person and the conversation are meant to stay connected. Assignment, private notes, tags, reminders and filters help a small team decide who owns the next step. Visitor context and cart details, where connected, reduce repeated questions. AI can stay as a draft that a teammate approves instead of sending immediately.

Those benefits need to be experienced rather than asserted against an unfamiliar competitor. Have two colleagues use both tools on the same handover. Ask the second person to find the earlier exchange and the right help article. Then ask someone who only answers occasionally to do it. If Orka makes that work meaningfully clearer, the paid team tier may be justified. If the free tawk.to setup already meets the need comfortably, there is no obligation to replace it.`),
 s('Availability is part of the customer experience.',`tawk.to documents online, away and offline widget states. Orka also communicates availability, with reply-time expectations and dedicated night, break-day and panic banners. These details help a visitor understand what kind of response is realistic. A small business should not need to pretend it has a continuously staffed call center just because its widget is always on the page.

Test after-hours behavior directly. Send a message when no human is available, leave the website and return later. Read the wording as a customer, not as the person who configured it. Does it explain what happens next? Does the AI identify the point where a person is needed? A clear expectation can be more valuable than an instant response that leaves the visitor unsure whether anyone is actually dealing with the problem.`,[2]),
 s('Our recommendation is deliberately not “paid must be better”.',`Keep tawk.to high on the shortlist when free core live chat and a knowledge base meet your needs, especially with many agents. Review the paid extras only if they solve a specific problem. A sustainable low-cost setup is a good outcome, and a fair comparison should acknowledge it without attaching an imaginary drawback.

Try Orka when you want its multi-project organization, knowledge-maintenance workflow and AI payment choices in one coherent workspace. Start with the free Solo plan and real documentation before choosing a team tier. The orca is admittedly a charming colleague, but the purchase should still earn its place: less repeated context, clearer ownership and answers your customers can actually use. If those improvements are not visible in your trial, a different tool may be the better choice.`)
 ]
},
{
 id:'bestchat',name:'BestChat',color:'#D2E0FF',symbol:'✳',theme:'Compare the product. Not just the family name.',
 intro:'BestChat and SmartBot are distinct offerings. This page compares Orka with BestChat’s published live-chat plans, while keeping AI allowances, seats and ecommerce claims attached to the right product.',
 bestOrka:'Several projects, a public help center and flexible AI provider billing.',bestRival:'Teams whose needs fit BestChat’s live-chat bundles and included AI-chat allowance.',
 priceNote:'BestChat plans, not SmartBot plans. Monthly bundles: Starter $10 / 1 seat, Basic $30 / 3 seats, Growth $60 / 6 seats. Above the selected seat limit, a different plan or quote is needed. Shopify recurring charges use 30-day cycles.',defaultPlan:2,
 sources:[source('BestChat pricing','https://bestchat.com/pricing.html'),source('BestChat developer listing','https://apps.shopify.com/bestchat'),source('BestChat product features','https://www.bestchat.com/features.html'),source('Separate SmartBot pricing','https://bestchat.com/smartbot-pricing.html')],
 proof:{'live-chat':['Live chat',2],'saved-replies':['Frequent replies',2],'attachments':['Files and screenshots',2],'assignment':['Transfers and departments',2],'visitor-profile':['Visitor identification and location',2],'analytics':['Traffic and service analytics',2],'mobile':['iOS, Android and web',2],'widget-brand':['Widget customization',2],'automatic-replies':['Included AI-chat quotas',0],'knowledge':['Knowledge-training quotas',0],'remove-branding':['Basic and Growth',0],'team-size':['Seat limits by plan',0]},
 sections:[
 s('The product name matters before the price.',`BestChat’s website describes a family that also includes SmartBot. The published plans for those products have different prices and allowances. A fair comparison should not take the cheapest price from one and the most ambitious capability from the other. This page uses BestChat’s own live-chat plan table and its developer-maintained Shopify listing as the price reference.

That distinction is useful for your evaluation too. Ask exactly which product is being demonstrated, which subscription unlocks the function and whether an integration requires another app. Orka’s proposition is one support workspace with team tiers and separate AI usage. That is easier to describe, but it still needs a real requirements check. A simple plan chart does not remove the need to test how the product handles your customers and your data.`,[0,1,3]),
 s('BestChat’s entry bundles can be inexpensive.',`The published BestChat plans include a free tier with one seat and eighty AI chats, Starter at $10 with one seat and three hundred AI chats, Basic at $30 with three seats and one thousand AI chats, and Growth at $60 with six seats and three thousand AI chats. Product and knowledge-training allowances also vary. The pricing is therefore neither a flat unlimited offer nor a simple per-agent multiplier.

Orka Pod costs $29 for up to three people, while Fleet is $99 for up to twenty. A six-person team may see an attractive base price in BestChat Growth; a larger team needs to verify a suitable BestChat offer. Our calculator stops at the selected bundle’s seat limit instead of inventing an extra-agent price. Compare the included AI allowance separately, because Orka’s managed AI uses tokens rather than an included count of chats.`,[0,1]),
 s('The live-chat toolbox is more than an AI label.',`BestChat’s feature page describes frequent replies, file sharing, screenshots, transfers, departments, visitor information, mobile clients and analytics. Those are useful capabilities for a team answering people throughout the day. It would be misleading to reduce the product to a basic bubble with no collaboration simply because its entry price is low.

Orka provides the conversation in a shared project workspace with assignment, tags, private notes, reminders and visitor context. The meaningful comparison is the full sequence of work. Receive a message, find the relevant context, bring in another person and close the loop. Try it again from a phone. A tool can have every item in that sequence and still feel different in practice, especially for the teammate who only helps with support occasionally.`,[2]),
 s('Training knowledge is not automatically a public help center.',`BestChat’s plans publish knowledge-training allowances for AI. That establishes a way to give the assistant information; it does not by itself establish a public help website with custom-domain publishing, collections and an article editor. An equivalent public publishing workflow was not verified in the sources reviewed here. We keep that distinction explicit rather than turning a training quota into a help-center checkmark.

Orka includes a public help center on every plan. Markdown articles can be organized into collections and sections, translated automatically and corrected manually. Visitors can search and read them inside the widget or on the help site, and the published knowledge also supports Orky. If you already have a documentation platform, compare the work of keeping it alongside BestChat with the work of importing supported content into Orka. Neither migration nor staying put should be assumed effortless.`,[0]),
 s('Included AI chats and token billing need different budgets.',`A bundle of AI chats can be convenient because the allowance is easy to recognize. The important follow-up is how the vendor counts a chat and what happens beyond the limit. Ask how long exchanges, retries and returning visitors are handled. The definition influences whether the included quantity matches your support volume.

Orka’s managed AI price names the model and separates input and output tokens. You can estimate the bill from measured usage or use your own provider key without an Orka markup. Neither structure is inherently better for every team. Short repetitive questions and long technical investigations can produce different results. Test both with actual examples and track whether the answer was useful, whether a person had to repair it and what unit appeared on the usage record.`,[0]),
 s('Be specific about ecommerce expectations.',`BestChat’s product family includes commerce-focused AI offerings, but capabilities and prices need to remain attached to the correct subscription. If the demonstration includes product recommendations or order-related behavior, ask whether that is BestChat, SmartBot or a connected feature in your chosen plan. The answer matters more than a general ecommerce label.

Apply the same standard to Orka. Visitor and cart context can help an agent understand a question; it is not a claim of automatic store transactions. Use a test involving a product, an order and an exception, and record what the software actually changes. If you need automatic refunds or cancellations, require a clear demonstration and permissions model. A persuasive reply is not evidence that the back-office task has been completed.`,[3]),
 s('Where the two choices make sense.',`BestChat can be a sensible option when its published seat, product, training and AI-chat allowances fit your business. Its lower paid entry points deserve acknowledgment. For a team already comfortable with the product, the relevant question is whether a specific missing workflow is causing enough friction to justify a move.

Orka is worth exploring when you want several projects under one subscription, a public multilingual knowledge library and a choice in how you pay for AI. The shared team context and editable drafts are useful when humans still own the final decision. Try one project first, keep the existing support channel available while you evaluate, and compare the whole path to a resolved question. That will tell you more than choosing the cheapest number or the most appealing mascot in isolation.`)
 ]
},
{
 id:'commslayer',name:'Commslayer',color:'#E6C8F3',symbol:'⌁',theme:'A serious Shopify challenger. A different Orka fit.',
 intro:'Commslayer combines an ecommerce helpdesk, AI, a help center and unlimited agents. Its free plan is a real alternative. Orka makes a different case around projects, knowledge and provider choice.',
 bestOrka:'Mixed websites and projects, a shared small team and token or own-key AI.',bestRival:'Shopify-centered teams wanting built-in commerce actions and unlimited agents.',
 priceNote:'Starting plan allowances: Free 300, Plus $39 / 800, Scale $299 / 6,000 billable conversations. Unlimited agents. AI and draft quotas, overages, voice and taxes must be checked separately. These are not unlimited-conversation prices.',defaultPlan:1,
 sources:[source('Commslayer pricing and allowances','https://www.commslayer.com/pricing'),source('Commslayer product FAQ','https://docs.commslayer.com/articles/1771000257-frequently-asked-questions'),source('Commslayer customer portal','https://www.commslayer.com/customer-portal-for-shopify'),source('Commslayer helpdesk','https://www.commslayer.com/helpdesk')],
 proof:{'live-chat':['Live chat and connected channels',0],'email-follow-up':['Email support',0],'team-size':['Unlimited agents',0],'shared-inbox':['Unified commerce helpdesk',3],'assignment':['Assignment rules',0],'saved-replies':['Macros',0],'automatic-replies':['AI quotas included; limits apply',0],'ai-drafts':['Draft quotas included',0],'summaries':['Plan-dependent AI summaries',0],'translation':['Plan-dependent translation',0],'help-center':['Help center on all plans',0],'help-domain':['Custom domain on all plans',0],'multilingual-help':['Storefront language support',2],'help-auto-translation':['Automatic translation',2],'help-translation-review':['Translations editable by hand; outdated markers not verified',2],'help-collections':['Searchable articles and categories',2],'help-ai':['Articles used by AI agent',2],'sdk':['Webhooks and custom actions',0],'visitor-profile':['Shopify customer context',3],'knowledge':['Knowledge used by AI',1]},
 sections:[
 s('This is a competitor worth taking seriously.',`Commslayer’s published offering includes unlimited agents, connected support channels, AI allowances and a help center with a custom domain. It also emphasizes Shopify operations. That combination means it can be a compelling option for an ecommerce team. We are not going to hide its free plan or pretend that public documentation is available only in Orka.

Orka’s case is different: one approachable support workspace for several kinds of project, with human collaboration, visitor context, editable knowledge and a choice between managed AI and your own provider key. If your business is entirely organized around Shopify, Commslayer’s focus may be useful. If the same people support apps, bookings, services and a store, the way Orka handles projects may deserve more weight. The starting point is the shape of your work, not a manufactured feature gap.`,[0,3]),
 s('Unlimited agents do not mean unlimited usage.',`Commslayer’s free plan lists three hundred billable conversations, three hundred AI messages and three hundred drafts. Plus starts at $39 with eight hundred conversations and higher AI allowances. Scale starts at $299 with six thousand conversations. Its published overages include additional conversation and AI-message charges. Agents are unlimited, but the operational units still have limits.

Orka charges by team tier: Solo free for one person, Pod $29 for three and Fleet $99 for twenty. Managed AI is separate. For a large group that handles a modest number of questions, Commslayer’s free or entry offer can look particularly attractive. For another workload, the usage allowance may matter more than seat count. Our calculator displays the starting subscription and labels the exclusions so that a low base number is not mistaken for a guaranteed total.`,[0]),
 s('Help centers are strong common ground.',`Commslayer lists a help center and custom domain on all plans. That is a genuine overlap with Orka, and an important one: customers should be able to find routine answers without waiting for a reply. If your shortlist includes these two products, the presence of a free help center is not enough to choose between them.

Orka’s confirmed publishing workflow includes Markdown, collections and sections, article search and filters, views and reactions, SEO fields, automatic translation and manual translation edits. Source changes mark translations as outdated. Published articles appear on the help site, can be read in the widget and support Orky. Compare these maintenance details directly with the Commslayer workflow you would use. Publishing the first ten articles is the easy test; revising them in several languages after a product change is the more revealing one.`,[0,1]),
 s('Commerce actions are a meaningful differentiator.',`Commslayer’s offering documents Shopify-oriented work, including order actions and connections to subscription tools. Its customer portal currently provides articles and contact options; native portal returns, tracking and order management are labeled coming soon. Existing order-editing tools and future portal actions should not be conflated. That is a reason to evaluate the product on actual store workflows.

Orka’s current catalogue confirms cart context and visitor information, not equivalent automatic refunds, subscription management or a full self-service order portal. We do not turn those unconfirmed capabilities into a checkmark. If they are essential, ask for a demonstration before selecting Orka. If your team mainly needs accurate answers and a human decision for exceptions, the conversation and knowledge workflow may matter more than a transactional portal. Both are reasonable priorities.`,[0,2]),
 s('AI quotas and token prices tell different stories.',`Commslayer publishes included AI-message and draft quantities. Orka’s managed AI is measured using the named model’s input and output tokens, or billed directly by your provider when you bring your own key. An AI-message allowance is not a fixed amount of model context, and a draft that a person edits is not necessarily equivalent to an autonomous resolution.

Take a representative batch of work and separate three jobs: suggesting a reply, answering a routine question automatically and handing an exception to a person. Record quality and usage for each. A bundle can be convenient when the included quantities align with the workload. Token pricing can be transparent when you have measured the actual consumption. The comparison should not pretend either method predicts cost perfectly without knowing the conversations you intend to run.`,[0]),
 s('Read roadmaps as roadmaps.',`Software pages sometimes show upcoming capabilities next to available ones. Commslayer’s pricing page labels some items as coming soon. Those labels matter. A planned channel or future automation should not become a current checkmark simply because it appears in the feature list. Confirm availability in the actual account and plan you are evaluating.

Apply the same discipline to Orka. The catalogue used here contains the capabilities established in the current product brief and site, including the help-center workflow confirmed by the product owner. It is not a promise of every possible integration. During your trial, write down the exact task you expect to perform and verify it. A clear boundary is more helpful than a confident sales sentence that merges a shipped feature, a custom integration and a future idea.`,[0]),
 s('Our recommendation follows your business, not our mascot.',`Choose Commslayer when Shopify support and store actions dominate your day, especially if unlimited agents and the included usage fit your team. Its free help center and AI allowances are real reasons to consider it. Calculate the likely overages and verify the actions you need, then judge the workflow with the people who will use it.

Choose Orka when a shared crew supports several projects and wants live conversations, public knowledge and AI assistance to feel consistent across them. The working-hours and emergency banners help keep human expectations clear, while reviewed drafts let your team decide what is actually sent. An orca is a pleasant bonus, but the serious decision is whether the workspace reduces repeated context and helps you answer accurately. If a competing product does that better for your store, this comparison should make that visible.`)
 ]
}
];
export const comparisonSections = (item) => [...item.sections,
 s('What the Orka subscription actually includes.',`Orka Solo is free for one person. Pod is $29 per month for up to three people, and Fleet is $99 per month for up to twenty. Unlimited projects and the help center are included across the plans. Message search, image sharing and analytics are paid-plan features. Fleet adds removal of Orka branding and a custom name for Orky. AI usage is a separate budget; using a provider key does not create an Orka markup.

The support toolkit includes live chat, live typing, saved replies, attachments, read receipts and email continuation. Your team can assign conversations, add private notes and mentions, use tags and filters, mark work resolved and set reminders. Visitor tools include a live map, a visitor list, profile information, recent page context, custom attributes and cart context when connected. Availability, reply-time expectations and night, break-day and panic banners explain when a human is around.

Orky can use your knowledge for automatic replies or drafts you review, help with writing shortcuts and summaries, translate conversations and hand over to a person. Widget branding, layout choices and seasonal themes sit alongside mobile apps, installation tools and an SDK. The detailed matrix below covers the full catalogue, including help-center publishing and translation maintenance. Features that depend on a plan or connected data are labeled, rather than silently promised everywhere.`),
 s('How to read this comparison.',`This guide is published by Orka, not an independent review site. Competitor facts come from the linked official product pages, documentation and developer-maintained listings checked on 18 September 2026. Our recommendations and trial ideas are our analysis. Pricing can change, and a negotiated offer or annual commitment may differ from the monthly examples shown here.

A row marked “Not verified” means the reviewed sources did not establish that exact capability. It does not mean the competitor cannot do it. We distinguish similar functions where needed: a typing indicator is not necessarily a preview of unsent text, an AI knowledge source is not automatically a public help center, and viewing a cart is not the same as changing an order. Ask the vendor to demonstrate the details that are essential to your team.

We compare published capabilities without making claims about certifications, ownership structure or data location that the evidence does not establish. The only deliberately unserious category is the orca connection. For everything else, bring a real support example, use the right plan and check the result. A fair comparison should help you choose well, even when the right choice is not Orka.`)
];
