import {signup,marineIcon,faqSection,faqSchema} from './site-chrome.mjs';
export const pricingFaqs=[
 ['Do I pay for every project?','No. Unlimited projects are included in Solo, Pod and Fleet. Add the SaaS products, apps, stores and websites you run to the same workspace. Your plan depends on team size and features, not your number of launches.'],
 ['What is included in the free plan?','Solo is for one person and includes unlimited projects, live chat, visitor context and the public multilingual help center with custom-domain publishing. Message search, image sharing and analytics start on Pod. AI usage is separate; Solo conversation translation requires your own provider key.'],
 ['Which plan fits a team of four or ten?','Fleet is $99 per month for up to twenty people. Pod covers up to three people for $29 per month. The price is for the bundle, not an amount multiplied by each included person.'],
 ['Is the help center really free on every plan?','Yes. Public publishing, custom domain, Markdown articles, collections, automatic translation, manual corrections and the widget Help tab are included across the plans. Published knowledge can also inform Orky.'],
 ['Is AI included in the subscription price?','Managed AI usage is separate from the team subscription. The standard API rate of the named model is multiplied by two, with input and output tokens counted separately. The calculator estimates conversations of ten customer messages and ten AI replies, and shows its token assumptions.'],
 ['Can I bring my own OpenAI or Anthropic key?','Yes. With your own supported provider key, you pay the provider directly and Orka adds no markup. Provider rates and terms apply. A ChatGPT or Claude consumer subscription is not an API credit balance.'],
 ['Why not quote a fixed AI price per conversation?','A short greeting and a long technical exchange consume different amounts of input and output. Knowledge and conversation history also add context. Use our conversation calculator as a planning example: ten customer messages plus ten AI replies, with adjustable answer length. Actual billing still uses tokens.'],
 ['Can I remove the Orka branding and rename Orky?','Yes, on Fleet. You can remove Orka branding and give the AI agent a custom name. The other plans retain the corresponding Orka branding.'],
 ['Does every teammate see every project?','You choose which projects each teammate can access. The shared inbox can show conversations together or filtered by project, so one crew can work across a portfolio without losing context.'],
 ['Do I need to use automatic AI replies?','No. You can answer yourself, ask Orky for a draft and review it, or enable automatic replies when useful. Human takeover and private notes help keep responsibility with your team.'],
 ['What if I have more than twenty people?','Contact hello@orka.chat with your team size and project setup. Fleet’s published price covers up to twenty people; this page does not invent an additional-seat rate or an enterprise package.'],
 ['What about taxes, cancellation and refunds?','The prices on this page are in US dollars. Applicable taxes and the billing details are shown at checkout. The Terms and Conditions explain renewal, cancellation and refund rules. Contact hello@orka.chat if you need help with an existing subscription.']
];
export function pricingBody({aiCalculator,finalCta}){
 const plans=[
 {name:'Solo',price:0,icon:'sail',tag:'YOU, YOUR IDEAS, YOUR INBOX',people:'1 person',copy:'For the founder wearing every hat.',items:['Unlimited projects','Live chat and visitor context','Free multilingual help center','Your own help-center domain','Bring your own AI key'],button:'Start free'},
 {name:'Pod',price:29,icon:'buoy',tag:'A LITTLE CREW. A LOT GOING ON.',people:'Up to 3 people',copy:'For a small team building together.',items:['Everything in Solo','Room for 3 teammates','Message search','Image sharing','Support analytics'],button:'Choose Pod'},
 {name:'Fleet',price:99,icon:'anchor',tag:'MORE HANDS. THE SAME HOME.',people:'Up to 20 people',copy:'For your products and the people behind them.',items:['Everything in Pod','Room for 20 teammates','Remove Orka branding','Give Orky a custom name','Unlimited projects, still'],button:'Choose Fleet'}
 ];
 return `<section class="c-pricing-hero"><div class="ed-wrap"><span class="ed-kicker">ONE INBOX. UNLIMITED PROJECTS.</span><h1>Price your crew.<br><em>Not your next idea.</em></h1><p>A SaaS, an app, a store, one more side project.<br>They all belong here. Choose the room your team needs.</p><div class="c-pricing-badges"><span>${marineIcon('sail')} Unlimited projects</span><span>${marineIcon('shell')} Free help center</span><span>${marineIcon('wave')} Optional AI</span></div></div></section><section class="ed-wrap c-plan-grid" aria-label="Orka monthly plans">${plans.map(p=>`<article class="c-plan ${p.name==='Pod'?'c-plan-featured':''}"><span class="ed-kicker">${p.tag}</span><div class="c-plan-name">${marineIcon(p.icon)}<h2>${p.name}</h2></div><p>${p.copy}</p><div class="c-plan-price"><strong>$${p.price}</strong><span>/ month</span></div><b class="c-plan-people">${p.people}</b><a class="ed-button lime" href="${signup}">${p.button} ↗</a><ul>${p.items.map(x=>`<li><span>✓</span>${x}</li>`).join('')}</ul><small>AI usage separate. Taxes may apply.</small></article>`).join('')}</section><section class="ed-wrap c-plan-table"><div class="c-section-head"><div><span class="ed-kicker">WHAT COMES ABOARD</span><h2>The plans, side by side.</h2></div><p>Every plan starts with the same idea: one place for the people behind all your projects.</p></div><div class="c-table-scroll" tabindex="0" role="region" aria-label="Orka plan features"><table class="c-table"><thead><tr><th scope="col">Included</th><th scope="col">Solo</th><th scope="col">Pod</th><th scope="col">Fleet</th></tr></thead><tbody>${[
 ['Monthly subscription','$0','$29','$99'],['People','1','Up to 3','Up to 20'],['Projects','Unlimited','Unlimited','Unlimited'],['Live chat & visitor context','Included','Included','Included'],['Public multilingual help center','Included','Included','Included'],['Help-center custom domain','Included','Included','Included'],['Markdown, collections & translations','Included','Included','Included'],['Message search','—','Included','Included'],['Image sharing','—','Included','Included'],['Analytics','—','Included','Included'],['Remove Orka branding','—','—','Included'],['Custom name for Orky','—','—','Included'],['Conversation translation','Own provider key required','AI usage applies','AI usage applies'],['Managed AI','Usage billed separately','Usage billed separately','Usage billed separately'],['Bring your own AI key','No Orka markup','No Orka markup','No Orka markup']
 ].map(row=>`<tr><th scope="row">${row[0]}</th>${row.slice(1).map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div><a class="c-source" href="/features">Explore the complete feature catalogue ↗</a></section><section class="c-portfolio ed-wrap"><div><span class="ed-kicker">THREE PROJECTS. STILL ONE PLAN.</span><h2>Launch another product.<br>Keep the same support home.</h2><p>Three people supporting one website use Pod. The same three people supporting ten projects can still use Pod. Add your project, connect its widget and answer with the same crew.</p><p>AI usage depends on the work it does, so it remains a separate, visible part of the budget.</p></div><div class="c-price-example"><span>Your SaaS + your store + your new app</span><strong>$29<small>/ month</small></strong><p>Orka Pod · up to 3 people<br>Unlimited projects · AI separate</p><a href="${signup}">Start bringing them together ↗</a></div></section>${aiCalculator()}${faqSection(pricingFaqs,{title:'Fair questions.<br>Clear answers.'})}${faqSchema(pricingFaqs)}${finalCta('Your next idea is welcome.<br>Your inbox is ready.')}`;
}
