import {plans} from './plan-copy.mjs';
import {signup,marineIcon,faqSection,faqSchema} from './site-chrome.mjs';
import {projectHelp,projectDialog,byokSpotlight} from './pricing-explainers.mjs';
export const pricingFaqs=[
 ['What counts as a project?','A project can be a SaaS, an ecommerce store, a vibe-coded website or part of the same product. For example, make your SaaS landing page one project for the marketing team and its webapp another for technical support. Each project has its own widget, settings and team access, with conversations in one shared inbox.'],
 ['Do I pay for every project?','No. Unlimited projects are included in Free, Pro and Max. Add the SaaS products, apps, stores and websites you run to the same workspace. Your plan depends on team size and features, not your number of launches.'],
 ['What is included in the free plan?','Free includes one team member, unlimited projects, live chat and email follow-up, custom visitor data through the SDK and API, the multilingual help center with a custom domain, and the iOS and Android apps. AI replies, conversation translation, message search, image sharing and analytics start on Pro.'],
 ['Which plan fits a team of four or ten?','Max is $99 per month for up to twenty people. Pro covers up to three people for $29 per month. The price is for the bundle, not an amount multiplied by each included person.'],
 ['Is the help center really free on every plan?','Yes. Public publishing, custom domain, Markdown articles, collections, automatic translation, manual corrections and the widget Help tab are included across the plans. Published knowledge can also inform Orky.'],
 ['Is AI included in the subscription price?','Managed AI usage is separate from the team subscription. The standard API rate of the named model is multiplied by two, with input and output tokens counted separately. The calculator estimates conversations of ten customer messages and ten AI replies, and shows its token assumptions.'],
 ['Can I use an OpenAI, Anthropic or OpenRouter API key?','Yes. On Pro and Max, connect an OpenAI, Anthropic or OpenRouter API key. You pay that provider directly for usage; Orka adds no markup. Or choose Orka-managed AI and use Orky without connecting a key. Provider API usage is separate from a ChatGPT or Claude consumer subscription.'],
 ['Do I need an API key to use Orky?','No. On Pro or Max, select Orka-managed AI and Orka handles access to the model. AI usage is billed separately at the displayed model rates. Bringing your own OpenAI, Anthropic or OpenRouter key is an option, not a requirement.'],
 ['Can one person choose Pro?','Yes. Free is for human support. Choose Pro when you want AI drafts, automatic replies, conversation translation, search or analytics, even if you are the only person answering. Pro includes room for up to three people.'],
 ['Why not quote a fixed AI price per conversation?','A short greeting and a long technical exchange consume different amounts of input and output. Knowledge and conversation history also add context. Use our conversation calculator as a planning example: ten customer messages plus ten AI replies, with adjustable answer length. Actual billing still uses tokens.'],
 ['Can I remove the Orka branding and customize Orky?','Yes, on Max. You can remove Orka branding and give the AI agent your own name and image. The other plans retain the corresponding Orka branding.'],
 ['Does every teammate see every project?','You choose which projects each teammate can access. The shared inbox can show conversations together or filtered by project, so one crew can work across a portfolio without losing context.'],
 ['Do I need to use automatic AI replies?','No. You can answer yourself, ask Orky for a draft and review it, or enable automatic replies when useful. Human takeover and private notes help keep responsibility with your team.'],
 ['What if I have more than twenty people?','Contact hello@orka.chat with your team size and project setup. Max’s published price covers up to twenty people; this page does not invent an additional-seat rate or an enterprise package.'],
 ['What about taxes, cancellation and refunds?','The prices on this page are in US dollars. Applicable taxes and the billing details are shown at checkout. The Terms and Conditions explain renewal, cancellation and refund rules. Contact hello@orka.chat if you need help with an existing subscription.']
];
export function pricingBody({aiCalculator,finalCta}){

 return `<section class="c-pricing-hero"><div class="ed-wrap"><span class="ed-kicker">ONE INBOX. UNLIMITED PROJECTS.</span><h1>Every product included.<br><em>Choose your crew.</em></h1><p>Start with Free. Add an AI teammate with Pro.<br>Make room for your whole team with Max. Every plan includes unlimited projects.</p><div class="c-pricing-badges"><span>${marineIcon('sail')} Unlimited projects ${projectHelp()}</span><span>${marineIcon('shell')} Free help center</span><a class="pricing-byok-badge" href="#bring-your-own-key">${marineIcon('orca')} Bring your own key · 0% markup ↗</a></div></div></section><section class="ed-wrap c-plan-grid" aria-label="Orka monthly plans">${plans.map(p=>`<article data-orka-plan-card="${p.name}" class="c-plan ${p.name==='Pro'?'c-plan-featured':''}"><span class="ed-kicker">${p.tag}</span><div class="c-plan-name">${marineIcon(p.icon)}<h2>${p.name}</h2></div><p>${p.copy}</p><div class="c-plan-price"><strong>$${p.price}</strong><span>/ month</span></div><b class="c-plan-people">${p.people}</b><a class="ed-button lime" href="${signup}">${p.button} ↗</a><ul>${['Unlimited projects',...p.items].map(x=>`<li><span>✓</span><div>${x}${x==='Unlimited projects'?' '+projectHelp():''}</div></li>`).join('')}</ul>${p.name!=='Free'?'<a class="plan-byok-link" href="#bring-your-own-key">Your key or Orka AI ↗</a>':''}<small>${p.footnote} Taxes may apply.</small></article>`).join('')}</section><div class="ed-wrap">${byokSpotlight({calculator:'#ai-pricing'})}</div><section class="ed-wrap c-plan-table"><div class="c-section-head"><div><span class="ed-kicker">WHAT COMES ABOARD</span><h2>The plans, side by side.</h2></div><p>Every plan starts with the same idea: one place for the people behind all your projects.</p></div><div class="c-table-scroll" tabindex="0" role="region" aria-label="Orka plan features"><table class="c-table"><thead><tr><th scope="col">Included</th><th scope="col">Free</th><th scope="col">Pro</th><th scope="col">Max</th></tr></thead><tbody>${[
 ['Monthly subscription','$0','$29','$99'],['Team members','1','Up to 3','Up to 20'],['Projects','Unlimited','Unlimited','Unlimited'],['Live chat & email follow-up','Included','Included','Included'],['Custom visitor data · SDK & API','Included','Included','Included'],['iOS & Android apps','Included','Included','Included'],['Public multilingual help center','Included','Included','Included'],['Help-center custom domain','Included','Included','Included'],['Markdown, collections & article translations','Included','Included','Included'],['AI drafts, auto-replies & reply buttons','—','Included · AI usage separate','Included · AI usage separate'],['Two-way conversation translation','—','Included · AI usage separate','Included · AI usage separate'],['AI summaries & urgency scores','—','Included · AI usage separate','Included · AI usage separate'],['Message search & image sharing','—','Included','Included'],['Analytics & live visitor map','—','Included','Included'],['Remove Orka branding','—','—','Included'],['Custom name & image for Orky','—','—','Included'],['Orka-managed AI · no key needed','—','Usage billed separately','Usage billed separately'],['Your OpenAI, Anthropic or OpenRouter key','—','No Orka markup','No Orka markup']
 ].map(row=>`<tr><th scope="row">${row[0]}${row[0]==='Projects'?' '+projectHelp():''}</th>${row.slice(1).map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div><a class="c-source" href="/features">Explore the complete feature catalogue ↗</a></section><section class="c-portfolio ed-wrap"><div><span class="ed-kicker">THREE PROJECTS. STILL ONE PLAN.</span><h2>Launch another product.<br>Keep the same support home.</h2><p>Three people supporting one website use Pro. The same three people supporting ten projects can still use Pro. Add your project, connect its widget and answer with the same crew.</p><p>AI usage depends on the work it does, so it remains a separate, visible part of the budget.</p></div><div class="c-price-example"><span>Your SaaS + your store + your new app</span><strong>$29<small>/ month</small></strong><p>Orka Pro · up to 3 people<br>Unlimited projects · AI separate</p><a href="${signup}">Start bringing them together ↗</a></div></section>${aiCalculator()}${faqSection(pricingFaqs,{title:'Fair questions.<br>Clear answers.'})}${faqSchema(pricingFaqs)}${finalCta('Your next idea is welcome.<br>Your inbox is ready.')}${projectDialog()}`;
}
