import {plans,planArtwork,planFeatureList,planIcon,featureTable} from './plan-copy.mjs';
import {signup,marineIcon,faqSection,faqSchema} from './site-chrome.mjs';
import {projectHelp,projectDialog,byokSpotlight} from './pricing-explainers.mjs';
export const pricingFaqs=[
 ['What counts as a project?','A project can be a SaaS, an ecommerce store, a vibe-coded website or part of the same product. For example, make your SaaS landing page one project for the marketing team and its webapp another for technical support. Each project has its own widget, settings and team access, with conversations in one shared inbox.'],
 ['Do I pay for every project?','No. Unlimited projects are included in Free, Light, Pro and Max. Add the SaaS products, apps, stores and websites you run to the same workspace. Your plan depends on team size and features, not your number of launches.'],
 ['What is included in the free plan?','Free includes one team member, unlimited projects, live chat and email follow-up, live typing preview, imports, widget designs, SDK and custom visitor data, the help center and mobile apps. Light adds team tools and analytics; AI features start on Pro.'],
 ['Which plan fits a team of four or ten?','Max is €99 per month with 12 team members included. Light is €9.99 for two people; Pro is €29 for three. On Max, each member beyond the included 12 costs €8 per month.'],
 ['Is the help center really free on every plan?','Yes. Publish your help center on every plan, including Free. Import knowledge from Crisp, GitBook, Intercom, Gleap or Help Scout. AI help center translation is available on Pro and Max, with AI usage billed separately.'],
 ['Is AI included in the subscription price?','Managed AI usage is separate from the team subscription. The standard API rate of the named model is multiplied by two, with input and output tokens counted separately. The calculator estimates conversations of ten customer messages and ten AI replies, and shows its token assumptions.'],
 ['Can I use an OpenAI, Anthropic or OpenRouter API key?','Yes. On Pro and Max, connect an OpenAI, Anthropic or OpenRouter API key. You pay that provider directly for usage; Orka adds no markup. Or choose Orka-managed AI and use Orky without connecting a key. Provider API usage is separate from a ChatGPT or Claude consumer subscription.'],
 ['Do I need an API key to use Orky?','No. On Pro or Max, select Orka-managed AI and Orka handles access to the model. AI usage is billed separately at the displayed model rates. Bringing your own OpenAI, Anthropic or OpenRouter key is an option, not a requirement.'],
 ['Can one person choose Pro?','Yes. Choose any plan for its features, even if you work alone. Light adds saved replies, search, files, scheduling, reminders and analytics; Pro adds AI drafts, auto-replies, handoff controls and AI translation. Pro includes up to three people.'],
 ['Why not quote a fixed AI price per conversation?','A short greeting and a long technical exchange consume different amounts of input and output. Knowledge and conversation history also add context. Use our conversation calculator as a planning example: ten customer messages plus ten AI replies, with adjustable answer length. Actual billing still uses tokens.'],
 ['Can I remove the Orka branding and customize Orky?','Yes, on Max. You can remove Orka branding and give the AI agent your own name and image. The other plans retain the corresponding Orka branding.'],
 ['Does every teammate see every project?','On Light, Pro and Max, assign teammates to specific projects and control the features they can access within each project. Free has one team member, so team permissions do not apply. Conversations still come together in one shared inbox.'],
 ['Do I need to use automatic AI replies?','No. You can answer yourself, ask Orky for a draft and review it, or enable automatic replies when useful. Human takeover and private notes help keep responsibility with your team.'],
 ['Can I add more team members?','Yes, on Max. The €99 monthly subscription includes 12 members; each additional member is €8 per month. For example, 15 members cost €123 per month, before AI usage and applicable taxes. Free, Light and Pro have fixed limits of 1, 2 and 3 members.'],
 ['What about taxes, cancellation and refunds?','Plan prices are in euros. The AI calculator labels its model-rate estimates separately in US dollars. Applicable taxes and the billing details are shown at checkout. The Terms and Conditions explain renewal, cancellation and refund rules. Contact hello@orka.chat if you need help with an existing subscription.']
];
export function pricingBody({aiCalculator,finalCta}){

 return `<section class="c-pricing-hero"><div class="ed-wrap"><span class="ed-kicker">ONE INBOX. UNLIMITED PROJECTS.</span><h1>Every product included.<br><em>Choose your crew.</em></h1><p>Start free. Share the work with Light. Add AI with Pro.<br>Grow your team with Max. Unlimited projects, whichever you choose.</p><div class="c-pricing-badges"><span>${marineIcon('sail')} Unlimited projects ${projectHelp()}</span><span>${marineIcon('shell')} Free help center</span><a class="pricing-byok-badge" href="#bring-your-own-key">${marineIcon('orca')} Bring your own key · 0% markup ↗</a></div></div></section><section class="ed-wrap c-plan-grid" aria-label="Orka monthly plans">${plans.map(p=>`<article data-orka-plan-card="${p.name}" class="c-plan ${p.name==='Pro'?'c-plan-featured':''}">${planArtwork(p,"c-plan-art")}<span class="ed-kicker">${p.tag}</span><div class="c-plan-name">${marineIcon(p.icon)}<h2>${p.name}</h2></div><p>${p.copy}</p><div class="c-plan-price"><strong>€${p.price}</strong><span>/ month</span></div><b class="c-plan-people">${p.people}</b><a class="ed-button lime" href="${signup}">${p.button} ↗</a><div class="plan-projects">${planIcon('layers')}Unlimited projects ${projectHelp()}</div>${planFeatureList(p)}${p.ai?'<a class="plan-byok-link" href="#bring-your-own-key">Your key or Orka AI ↗</a>':''}<small>${p.footnote} Taxes may apply.</small></article>`).join('')}</section><div class="ed-wrap">${byokSpotlight({calculator:'#ai-pricing'})}</div><section class="ed-wrap c-plan-table" id="compare-plans"><div class="c-section-head"><div><span class="ed-kicker">WHAT COMES ABOARD</span><h2>The plans, side by side.</h2></div><p>One shared inbox on every plan. Choose the people, tools and AI you need. On mobile, swipe to compare all four plans.</p></div>${featureTable(projectHelp)}<a class="c-source" href="/features">Explore the complete feature catalogue ↗</a></section><section class="c-portfolio ed-wrap"><div><span class="ed-kicker">THREE PROJECTS. STILL ONE PLAN.</span><h2>Launch another product.<br>Keep the same support home.</h2><p>Three people supporting one website use Pro. The same three people supporting ten projects can still use Pro. Add your project, connect its widget and answer with the same crew.</p><p>AI usage depends on the work it does, so it remains a separate, visible part of the budget.</p></div><div class="c-price-example"><span>Your SaaS + your store + your new app</span><strong>€29<small>/ month</small></strong><p>Orka Pro · up to 3 people<br>Unlimited projects · AI separate</p><a href="${signup}">Start bringing them together ↗</a></div></section>${aiCalculator()}${faqSection(pricingFaqs,{title:'Fair questions.<br>Clear answers.'})}${faqSchema(pricingFaqs)}${pricingSchema()}${finalCta('Your next idea is welcome.<br>Your inbox is ready.')}${projectDialog()}`;
}

function pricingSchema(){return `<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'SoftwareApplication',name:'Orka',applicationCategory:'BusinessApplication',operatingSystem:'Web, iOS, Android',url:'https://orka.chat/pricing',offers:plans.map(p=>({'@type':'Offer',name:p.name,price:p.price,priceCurrency:'EUR',url:'https://orka.chat/pricing',description:p.people+' included. Unlimited projects. '+p.footnote,priceSpecification:{'@type':'UnitPriceSpecification',price:p.price,priceCurrency:'EUR',billingDuration:'P1M'}}))})}</script>`;}
